### PR TITLE
[storage] Add `Location`/`Position` documentation; prevent panics

### LINKED ISSUE #1749: Multiple panics in the storage
The code panics in the following locations:

- storage/src/adb/any/fixed/mod.rs:541
- storage/src/adb/any/variable/mod.rs:612
- storage/src/adb/current.rs:426
- storage/src/adb/immutable/mod.rs:610
- storage/src/metadata/storage.rs:311

- storage/src/mmr/location.rs:90
- storage/src/mmr/location.rs:153
- storage/src/mmr/location.rs:99
- storage/src/mmr/location.rs:108
- storage/src/mmr/location.rs:160
- storage/src/mmr/location.rs:117

- storage/src/mmr/position.rs:115
- storage/src/mmr/position.rs:142

I think that most of them are trivial for identification, but let me know if you need more information or steps to reproduce for some of them.

### PR DESCRIPTION
**Pull request by danlaine**
* Use `saturating_add` instead of `checked_add` to prevent panics on too-large input
* Add documentation to clarify that `Location` and `Position` operations panic on underflow/overflow

Resolves #1749

### CODE REVIEW

File: storage/src/adb/any/fixed/mod.rs [hunk 1]
```diff
@@ -538,7 +538,7 @@ impl<
         max_ops: NonZeroU64,
     ) -> Result<(Proof<H::Digest>, Vec<Operation<K, V>>), Error> {
         let op_count = Location::new(op_count);
-        let end_loc = std::cmp::min(op_count, start_loc.checked_add(max_ops.get()).unwrap());
+        let end_loc = std::cmp::min(op_count, start_loc.saturating_add(max_ops.get()));
```
Comment (roberto-bayardo) [inline storage/src/adb/any/fixed/mod.rs:541]: ~~Hmm, if we want to avoid panic here, seems better to return error than to return a proof that doesn't match the input?~~

Comment (roberto-bayardo) [reply storage/src/adb/any/fixed/mod.rs:541]: Ah never mind, I guess we have a max_ops so basically we return best-effort up to that, in which case saturating_add makes sense.
