### PR TITLE
[cryptography] Error on reading invalid bloom filter

### LINKED ISSUE #1747: Panic in cryptography/src/bloomfilter.rs:60
```
thread '<unnamed>' (607038) panicked at cryptography/src/bloomfilter.rs:60:32:
attempt to calculate the remainder with a divisor of zero
```

Steps to reproduce:

```
git checkout denis/fix-bl-fuzz
cd cryptography
cargo fuzz run bloomfilter_decode
```

### PR DESCRIPTION
**Pull request by danlaine**
`BloomFilter` expects `BloomFilter.bits.len() > 0` always holds. However, it's possible to call `read_cfg` with invalid value 0, resulting in a `BloomFilter` that violates this invariant.

This PR makes the config type `NonZeroU64` to prevent reading an invalid `BloomFilter`.

Resolves #1747

### CODE REVIEW

File: cryptography/fuzz/fuzz_targets/bloomfilter.rs [hunk 1]
```diff
@@ -33,7 +33,7 @@ fn fuzz(input: FuzzInput) {
     );
     let mut model: HashSet<Vec<u8>> = HashSet::new();
 
-    let cfg = (hashers, bits as u64);
+    let cfg = (hashers, NonZeroU64::new(bits as u64).unwrap());
```
Comment (patrick-ogrady) [inline cryptography/fuzz/fuzz_targets/bloomfilter.rs]: use `NZU64!` for this?

Comment (danlaine) [reply cryptography/fuzz/fuzz_targets/bloomfilter.rs]: Requires adding a dependency on `commonware-utils` in `Cargo.toml`. Probably better to avoid that at the cost of a few characters?

Comment (patrick-ogrady) [reply cryptography/fuzz/fuzz_targets/bloomfilter.rs]: That dep would just be in fuzzer (and we already depend on in cryptography)?

Comment (danlaine) [reply cryptography/fuzz/fuzz_targets/bloomfilter.rs]: I changed the `FuzzInput` fields to be `NonZero` so now we just use `.into()` and we don't need to use `NonZeroU64::new` or `NZU64!`

File: cryptography/src/bloomfilter.rs [hunk 2]
```diff
@@ -91,7 +91,7 @@ impl Write for BloomFilter {
 
 impl Read for BloomFilter {
     // The number of hashers and the number of bits that the bitmap must have.
-    type Cfg = (u8, u64);
+    type Cfg = (u8, NonZeroU64);
```
Comment (patrick-ogrady) [inline cryptography/src/bloomfilter.rs]: for the same rationale, should `u8` also be NonZeroU8?

File: cryptography/fuzz/fuzz_targets/bloomfilter.rs [hunk 3]
```diff
@@ -19,21 +19,17 @@ enum Op {
...
 
 fn fuzz(input: FuzzInput) {
-    let hashers = (input.hashers).max(1);
-    let bits = (input.bits).max(1);
-    let mut bf = BloomFilter::new(
-        NonZeroU8::new(hashers).unwrap(),
-        NonZeroUsize::new(bits.into()).unwrap(),
-    );
+    let hashers = input.hashers.get();
+    let mut bf = BloomFilter::new(NonZeroU8::new(hashers).unwrap(), input.bits.into());
```
Comment (patrick-ogrady) [inline cryptography/fuzz/fuzz_targets/bloomfilter.rs]: nit: isn't this already NonZeroU8?
