### PR TITLE
[reshare] Don't panic if `Dkg` message fails to decode

### LINKED ISSUE #1962: [reshare] Don't panic if the `DkgMessage` fails to parse
## Overview

We should just skip the message if it fails to decode here:

https://github.com/commonwarexyz/monorepo/blob/d2c8701405d3107339143b858070e7024ab622c1/examples/reshare/src/dkg/manager.rs#L354-L356

### PR DESCRIPTION
**Pull request by clabby**
## Overview

Drops any `Dkg` messages that fail to decode in the `DkgManager`.

closes #1962

### CODE REVIEW

File: examples/reshare/src/dkg/manager.rs [hunk 1]
```diff
@@ -374,18 +377,18 @@ where
...
                         warn!(round, "ignoring ack; not a dealer");
-                        return;
+                        continue;
                     };
 
                     // Verify index matches
                     let Some(player) = self.players.get(ack.player as usize) else {
                         warn!(round, index = ack.player, "invalid ack index");
-                        return;
+                        continue;
```
Comment (patrick-ogrady) [inline examples/reshare/src/dkg/manager.rs:386]: In a production setting, we may want to "block" on p2p here but we can defer that work.
