### PR TITLE
[runtime] Review Attributes

### LINKED ISSUE #3485: [runtime] Review Usage of Attributes on Metrics
In marshaled applications, we apply attributes aggressively. We should be sure this doesn't blow up memory usage (either by tracked tasks or something unexpected).

### PR DESCRIPTION
**Pull request by patrick-ogrady**
Closes: #3485
Related: #1110 + #3077 
Future Work: https://github.com/commonwarexyz/monorepo/issues/3585

### CODE REVIEW

File: runtime/src/lib.rs [hunk 1]
```diff
@@ -288,6 +285,38 @@ stability_scope!(BETA {
...
+    ///   is not inherited by child contexts.
+    ///
+    /// | Builder                 | Registered metric name | Registered metric labels | Registry isolation | Runtime task metrics | Tracing span                     |
+    /// | ----------------------- | :--------------------: | :----------------------: | :----------------: | :------------------: | :------------------------------: |
+    /// | `with_label`            | prefix                 | -                        | -                  | `name`               | `name` field when `with_span`    |
+    /// | `with_attribute`        | -                      | label dimension          | -                  | -                    | OTel attribute when `with_span`  |
+    /// | `with_scope`            | -                      | -                        | sub-registry       | -                    | -                                |
+    /// | `with_span`             | -                      | -                        | -                  | -                    | enables span creation            |
     pub trait Metrics: Clone + Send + Sync + 'static {
```
Comment (patrick-ogrady) [inline runtime/src/lib.rs:320]: At some point, it may make sense to rename this `Observability` (if we keep metrics/tracing coupled).

File: runtime/src/lib.rs [hunk 2]
```diff
@@ -435,6 +449,35 @@ stability_scope!(BETA {
...
+        ///
+        /// The flag is consumed by the next [`Spawner::spawn`] call on the returned
+        /// context (and on any clone of it). It is not inherited by child contexts
+        /// produced via [`Metrics::with_label`], [`Metrics::with_attribute`],
+        /// [`Metrics::with_scope`], or any of the `Spawner` builders: each such builder
+        /// resets the flag so the caller must opt in again for the next spawn.
+        ///
+        /// Enabling the span only affects tracing; it does not change which metrics
+        /// are registered, nor does it widen the cardinality of runtime task metrics.
+        fn with_span(&self) -> Self;
```
Comment (clabby) [inline runtime/src/lib.rs:465]: way better than `instrumented` :)

File: runtime/src/lib.rs [hunk 3]
```diff
@@ -288,6 +285,38 @@ stability_scope!(BETA {
...
 
     /// Interface to register and encode metrics.
+    ///
+    /// # Mental Model: Metrics vs Tracing
+    ///
+    /// A context carries multiple pieces of observability state, each
+    /// applied via a different builder. They compose freely, but they do
+    /// not all feed into the same sinks:
+    ///
+    /// - `name` (set by [`Metrics::with_label`]): prefix applied to metrics
```
Comment (patrick-ogrady) [inline runtime/src/lib.rs:295]: I don't love we need to document this so tightly (it is pretty opaque) but it does enable us to do what we need in many different environments, so I can't complain too much.

File: runtime/src/lib.rs [hunk 4]
```diff
@@ -288,6 +285,38 @@ stability_scope!(BETA {
...
+    ///   does not affect runtime task metrics and has no effect on tracing.
+    /// - `span` (set by [`Metrics::with_span`]): wraps the next spawned task
+    ///   in a `tracing` span populated from the current `name` and `attributes`.
+    ///   It never touches metrics. The flag is consumed by the next `spawn` and
+    ///   is not inherited by child contexts.
+    ///
+    /// | Builder                 | Registered metric name | Registered metric labels | Registry isolation | Runtime task metrics | Tracing span                     |
+    /// | ----------------------- | :--------------------: | :----------------------: | :----------------: | :------------------: | :------------------------------: |
+    /// | `with_label`            | prefix                 | -                        | -                  | `name`               | `name` field when `with_span`    |
+    /// | `with_attribute`        | -                      | label dimension          | -                  | -                    | OTel attribute when `with_span`  |
```
Comment (clabby) [inline runtime/src/lib.rs:317]: While you're in here, we should also add the attributes to the [`ValueSet`](https://docs.rs/tracing/latest/tracing/field/struct.ValueSet.html) of the `Span`.

See [`Span::record`](https://docs.rs/tracing/latest/tracing/struct.Span.html#method.record)

Comment (patrick-ogrady) [reply runtime/src/lib.rs:317]: This will also get bubbled into the trace we send to OTel (according to claude):

```
⏺ Yes — good catch. OTel backends actually see both: set_attribute adds the individual pairs directly to
  OtelData, and tracing_opentelemetry's layer also bridges the attributes tracing field (set via record) into
  the same OTel span as a string attribute. So on the OTel side you get:

  - round="7", epoch="2" — from set_attribute.
  - attributes="[(\"epoch\", \"2\"), (\"round\", \"7\")]" — from record via the tracing→OTel bridge.
```

Not sure there is a way around this?

**Review by clabby — APPROVED** [review]
