### PR TITLE
Fixes #1269: a memory leak in the deterministic runtime

### LINKED ISSUE #1269: [storage/fuzz] memory leak
```
	NEW_FUNC[1/28]: 0x55fcdfe55bd0  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x2d79bd0) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
	NEW_FUNC[2/28]: 0x55fcdfebd610  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x2de1610) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)

=================================================================
==11362==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 112 byte(s) in 1 object(s) allocated from:
    #0 0x55fcdfde6f64  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x2d0af64) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #1 0x55fce08060c5  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x372a0c5) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #2 0x55fce02215bd  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31455bd) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #3 0x55fce02a535c  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31c935c) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #4 0x55fce02a4c78  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31c8c78) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #5 0x55fce02a64a3  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31ca4a3) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #6 0x55fce02aaeb8  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31ceeb8) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #7 0x55fce02aa12b  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31ce12b) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #8 0x55fce02b26c0  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31d66c0) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #9 0x55fce02b9d19  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31ddd19) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #10 0x55fce02bae2a  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31dee2a) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #11 0x55fce02bbd97  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31dfd97) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #12 0x55fce02e1406  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x3205406) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #13 0x55fce02c3096  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31e7096) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #14 0x7f1ed782a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #15 0x7f1ed782a28a  (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #16 0x55fcdfd46ea4  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x2c6aea4) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)

Indirect leak of 96 byte(s) in 1 object(s) allocated from:
    #0 0x55fcdfde6f64  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x2d0af64) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #1 0x55fce0809899  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x372d899) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #2 0x55fce0221471  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x3145471) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #3 0x55fce02a535c  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31c935c) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #4 0x55fce02a4c78  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31c8c78) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #5 0x55fce02a64a3  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31ca4a3) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #6 0x55fce02aaeb8  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31ceeb8) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #7 0x55fce02aa12b  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31ce12b) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #8 0x55fce02b26c0  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31d66c0) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #9 0x55fce02b9d19  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31ddd19) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #10 0x55fce02bae2a  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31dee2a) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #11 0x55fce02bbd97  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31dfd97) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #12 0x55fce02e1406  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x3205406) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #13 0x55fce02c3096  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31e7096) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #14 0x7f1ed782a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #15 0x7f1ed782a28a  (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #16 0x55fcdfd46ea4  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x2c6aea4) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x55fcdfde6f64  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x2d0af64) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #1 0x55fce08081ac  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x372c1ac) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #2 0x55fce0222725  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x3146725) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #3 0x55fce02a535c  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31c935c) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #4 0x55fce02a4c78  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31c8c78) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #5 0x55fce02a64a3  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31ca4a3) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #6 0x55fce02aaeb8  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31ceeb8) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #7 0x55fce02aa12b  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31ce12b) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #8 0x55fce02b26c0  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31d66c0) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #9 0x55fce02b9d19  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31ddd19) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #10 0x55fce02bae2a  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31dee2a) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #11 0x55fce02bbd97  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31dfd97) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #12 0x55fce02e1406  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x3205406) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #13 0x55fce02c3096  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x31e7096) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)
    #14 0x7f1ed782a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #15 0x7f1ed782a28a  (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 42c84c92e6f98126b3e2230ebfdead22c235b667)
    #16 0x55fcdfd46ea4  (/home/runner/work/monorepo/monorepo/target/x86_64-unknown-linux-gnu/release/adb_current_operations+0x2c6aea4) (BuildId: d99cd2170e73d5ef18f31357a5c3c8bc7d4fcc2b)

SUMMARY: AddressSanitizer: 216 byte(s) leaked in 3 allocation(s).
INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.

MS: 2 ShuffleBytes-ChangeByte-; base unit: 3fe76a7e3a99f54c3c9f90d6c20462c4f353f46e
0x7,0xa6,0x0,0x69,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x29,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x69,0xe9,0x97,0x8d,0x69,0x69,0xff,0xff,0x5c,0x5c,0x5c,0x6b,0x6b,0x6b,0x6b,0x6b,0x6b,0x6b,0x6b,0x6b,0x6b,0x69,0x69,0x69,0x69,0x69,0x61,0x63,0x69,0x3d,0x69,0x69,0x69,0x69,0x30,0x69,0x69,0x69,0x69,0x69,0x69,0x69,0x63,0x63,0x63,0x63,0x63,0x63,0x63,0x63,0x5b,0x63,0x63,
\007\246\000i\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000)\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000i\351\227\215ii\377\377\\\\\\kkkkkkkkkkiiiiiaci=iiii0iiiiiiicccccccc[cc
artifact_prefix='storage/fuzz/artifacts/adb_current_operations/'; Test unit written to storage/fuzz/artifacts/adb_current_operations/leak-55a2cafb02963d[765](https://github.com/commonwarexyz/monorepo/actions/runs/16252969668/job/45885198372#step:8:766)18aa0cb0b927bcf6fab7a08
Base64: B6YAaQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKQAAAAAAAAAAAAAAAAAAAAAAaemXjWlp//9cXFxra2tra2tra2traWlpaWlhY2k9aWlpaTBpaWlpaWlpY2NjY2NjY2NbY2M=

────────────────────────────────────────────────────────────────────────────────

Failing input:

	storage/fuzz/artifacts/adb_current_operations/leak-55a2cafb02963d76518aa0cb0b927bcf6fab7a08

Output of `std::fmt::Debug`:

	FuzzInput {
	    operations: [
	        Update {
	            key: [
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                41,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	            ],
	            value: [
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                105,
	                233,
	                151,
	                141,
	                105,
	                105,
	                255,
	                255,
	                92,
	                92,
	                92,
	                107,
	                107,
	                107,
	                107,
	                107,
	                107,
	                107,
	                107,
	                107,
	                107,
	            ],
	        },
	        Commit,
	        Commit,
	        Commit,
	        Commit,
	        Commit,
	        Commit,
	        Update {
	            key: [
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	            ],
	            value: [
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	                0,
	            ],
	        },
	    ],
	}
```

### PR DESCRIPTION
**Pull request by evonide**
Please see description in https://github.com/commonwarexyz/monorepo/issues/1269#issuecomment-3079171015

### CODE REVIEW

File: runtime/src/deterministic.rs [hunk 1]
```diff
@@ -466,14 +466,16 @@ enum Operation {
...
-    tasks: Arc<Tasks>,
+    tasks: Weak<Tasks>,
 
     operation: Operation,
 }
 
 impl ArcWake for Task {
     fn wake_by_ref(arc_self: &Arc<Self>) {
-        arc_self.tasks.enqueue(arc_self.clone());
+        if let Some(tasks) = arc_self.tasks.upgrade() {
```
Comment (patrick-ogrady) [inline runtime/src/deterministic.rs:478]: nit: would you mind adding a brief comment to explain that this is ok to fail (and why)?

Comment (evonide) [reply runtime/src/deterministic.rs:478]: done

**Review by patrick-ogrady — APPROVED** [review]

**Comment by patrick-ogrady** [comment]
(Will let the slow benchmarks finish given how fundamental this change is before merging)
