### PR TITLE
[storage] Prevent overflow on `Location` to `Position` conversion

### LINKED ISSUE #1831: leaf_loc overflow at storage/src/mmr/position.rs:106
I think `adb::verify::verify_multi_proof` should not [panic](https://github.com/commonwarexyz/monorepo/blob/2764f4e0ea088bc9372f6cf5ae5161451070730a/storage/src/mmr/position.rs#L106) since it must handle arbitrary input, but it does.

To reproduce:
```
cargo fuzz run verify_multi_proof fuzz/artifacts/verify_multi_proof/crash-165f8d91f1917b8577a73b55574f7e8ce5b13cfb.txt
```

```
#![no_main]

use arbitrary::{Arbitrary, Unstructured};
use commonware_cryptography::{sha256::Digest, Sha256};
use commonware_storage::{
    adb::verify::verify_multi_proof,
    mmr::{Location, Position, Proof, StandardHasher as Standard},
};
use libfuzzer_sys::fuzz_target;

const MAX_DIGESTS: usize = 128;
const MAX_OPERATIONS: usize = 64;
const MAX_OPERATION_BYTES: usize = 512;

#[derive(Arbitrary, Debug)]
struct OperationInput {
    location: u64,
    payload: Vec<u8>,
}

#[derive(Arbitrary, Debug)]
struct FuzzInput {
    proof_size: u64,
    digests: Vec<[u8; 32]>,
    operations: Vec<OperationInput>,
    root: [u8; 32],
}

fn exercise(input: FuzzInput) {
    let mut hasher: Standard<Sha256> = Standard::new();

    let digests = input
        .digests
        .into_iter()
        .take(MAX_DIGESTS)
        .map(Digest::from)
        .collect::<Vec<_>>();

    let proof = Proof {
        size: Position::new(input.proof_size),
        digests,
    };

    let mut operations = Vec::new();
    for entry in input.operations.into_iter().take(MAX_OPERATIONS) {
        let mut payload = entry.payload;
        if payload.len() > MAX_OPERATION_BYTES {
            payload.truncate(MAX_OPERATION_BYTES);
        }
        operations.push((Location::new(entry.location), payload));
    }

    let root = Digest::from(input.root);
    let _ = verify_multi_proof(&mut hasher, &proof, &operations, &root);
}

fuzz_target!(|data: &[u8]| {
    let mut unstructured = Unstructured::new(data);
    let Ok(input) = FuzzInput::arbitrary(&mut unstructured) else {
        return;
    };
    exercise(input);
});
```

[crash-165f8d91f1917b8577a73b55574f7e8ce5b13cfb.txt](https://github.com/user-attachments/files/22751907/crash-165f8d91f1917b8577a73b55574f7e8ce5b13cfb.txt)

### PR DESCRIPTION
**Pull request by danlaine**
Work in progress.

This PR resolves #1831. It ensures that `pub` functions don't panic when given invalid location bounds. More generally, this PR replaces panics with errors in order to reduce the number of places an invalid user input can crash the program.

Change summary:

* Add `const MAX_LOCATION`. Any location larger than this would cause an MMR whose size fails `check_validity`.
* Change `Location::new` return type to `Option<Self>`. Returns `None` if the `Location > MAX_LOCATION`.
* Replace `From<Location> for Position` with `TryFrom` to prevent usage of invalid `Location`.
* Add `Location::new_unchecked` which is `pub(crate)` and used internally in the crate for trusted inputs and tests.
* Replace assertions with error returns in public proof generation/verification methods.

### CODE REVIEW

File: storage/src/adb/any/fixed/mod.rs [hunk 1]
```diff
@@ -332,10 +332,21 @@ impl<
...
 
-    /// Get the value of the operation with location `loc` in the db. Returns [Error::OperationPruned]
-    /// if the location precedes the oldest retained location. The location is otherwise assumed
-    /// valid.
+    /// Get the value of the operation with location `loc` in the db.
+    ///
+    /// # Errors
+    ///
+    /// Returns [crate::mmr::Error::LocationOverflow] if `loc` > [crate::mmr::MAX_LOCATION].
+    /// Returns [Error::OperationPruned] if the location precedes the oldest retained location.
```
Comment (roberto-bayardo) [inline storage/src/adb/any/fixed/mod.rs:340]: Feels inconsistent to panic when loc >= op_count but return error if it overflows. I'm actually not sure why this method is public TBH (outside of the keyless DB).  I wonder if we can lower its visibility and just make it panic in both cases.

Comment (roberto-bayardo) [reply storage/src/adb/any/fixed/mod.rs:340]: as discussed elsewhere this will be cleaned up in a subsequent PR

File: storage/src/mmr/position.rs [hunk 2]
```diff
@@ -93,17 +93,39 @@ impl From<Position> for u64 {
     }
 }
 
-/// Returns the position of the leaf at the given location in an MMR.
+/// Try to convert a [Location] to a [Position].
```
Comment (roberto-bayardo) [inline storage/src/mmr/position.rs:96]: I don't think try_from is necessary given one shouldn't be creating overflowing locations in the first place.

Comment (roberto-bayardo) [reply storage/src/mmr/position.rs:96]: I guess this does the input validation of Locations just in case someone does abuse it, so let's leave it.
