### PR TITLE
[storage] Add `journal::Contiguous`; implement for `journal::Fixed` and `journal::Variable`

### LINKED ISSUE #1718: [storage/journal] Make Contiguous Variable
Unlike `journal::fixed`, `journal::variable` does not assume that you are working over a contiguous global log (just one per section). The rationale for this was that you need to store consensus messages in multiple views and you want to prune them independently (if you added to a contiguous log, you'd have to track the lowest view active at some index): https://github.com/commonwarexyz/monorepo/blob/9a87cd8e17fdd066d46fff0a4d00d307f4572e3c/consensus/src/threshold_simplex/actors/voter/actor.rs#L1072-L1108

We should make a wrapper around `journal::variable` that provides this contiguous functionality. This would make implementing much of the `adb-related` logic MUCH simpler (as there is a ton of logic mapping index to location).

### PR DESCRIPTION
**Pull request by danlaine**
This PR resolves #1718.

### CODE REVIEW

File: storage/src/journal/contiguous/variable.rs [hunk 1]
```diff
@@ -0,0 +1,1441 @@
...
+        data: &variable::Journal<E, V>,
+        locations: &mut fixed::Journal<E, Location>,
+        items_per_section: u64,
+    ) -> Result<(u64, u64), Error> {
+        // === Step 1: Scan data journal to determine expected state ===
+
+        let (expected_locations_size, expected_locations_oldest_pos) = if data.blobs.is_empty() {
+            // No data blobs → journal is empty or fully pruned
+            // Size comes from locations journal.
+            (locations.size().await?, locations.size().await?)
```
Comment (danlaine) [inline storage/src/journal/contiguous/variable.rs]: Note that it's not possible to distinguish these scenarios:

1. Data partition was errantly deleted (corruption)
2. Journal is empty
3. Journal crashed while pruning to empty -- data journal was emptied but locations wasn't

The data journal is authoritative, but the _lack_ of a data journal can mean several things happened.

We handle all of these cases by using whatever is in the locations journal.

File: storage/src/journal/contiguous/variable.rs [hunk 2]
```diff
@@ -0,0 +1,1436 @@
...
+
+impl Write for Location {
+    fn write(&self, buf: &mut impl BufMut) {
+        buf.put_u64(self.section);
+        buf.put_u32(self.offset);
+    }
+}
+
+impl FixedSize for Location {
+    const SIZE: usize = 12; // u64 + u32
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: nit: write out as `u64::SIZE + u32::SIZE`

File: storage/src/journal/contiguous/variable.rs [hunk 3]
```diff
@@ -0,0 +1,1436 @@
...
+            oldest_retained_pos,
+        })
+    }
+
+    /// Rewind the journal to the given size, discarding items from the end.
+    ///
+    /// After rewinding to size N, the journal will contain exactly N items,
+    /// and the next append will receive position N.
+    ///
+    /// # Crash Safety
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: 🙏

File: storage/src/journal/contiguous/variable.rs [hunk 4]
```diff
@@ -0,0 +1,1436 @@
...
+        // Read the location of the first item to discard (at position 'size').
+        let discard_location = self.locations.read(size).await?;
+
+        // Rewind locations journal FIRST (opposite order from append!)
+        // This ensures crash-safety: if we crash after locations.rewind() but before
+        // data.rewind(), init() will see locations behind data and repair it by
+        // appending missing location entries. If we did data first, locations would
+        // be ahead (unrecoverable corruption).
+        self.locations.rewind(size).await?;
+
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs:229]: nit: remove `\n`

File: storage/src/journal/contiguous/variable.rs [hunk 5]
```diff
@@ -0,0 +1,1436 @@
...
+            return Ok(false);
+        }
+
+        // Cap min_position to size to maintain the invariant oldest_retained_pos <= size
+        let min_position = min_position.min(self.size);
+
+        // Calculate section number
+        let min_section = min_position / self.items_per_section;
+
+        // Prune data journal FIRST, then locations journal.
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: tbh: I would've expected modifying `locations` first to remain consistent with `rewind`?

File: storage/src/journal/contiguous/variable.rs [hunk 6]
```diff
@@ -0,0 +1,1436 @@
...
+        // === Handle non-empty data journal case ===
+        let (data_oldest_pos, data_size) = {
+            // Data exists → count items
+            let first_section = *data.blobs.first_key_value().unwrap().0;
+            let last_section = *data.blobs.last_key_value().unwrap().0;
+            let oldest_pos = first_section * items_per_section;
+
+            // Count items in last section by replaying it
+            let items_in_last_section = {
+                let stream = data.replay(last_section, 0, REPLAY_BUFFER_SIZE).await?;
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: I suppose we know that replaying the last section is sufficient because we must successfully sync before entering it?

File: storage/src/journal/contiguous/variable.rs (hunk 5 above)
Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs]: (I'm assuming this was done for a particular recovery case)

File: storage/src/journal/contiguous/variable.rs [hunk 7]
```diff
@@ -0,0 +1,1436 @@
...
+        // Apply any operations that are missing from the locations journal.
+        if locations_size < data_size {
+            Self::add_missing_locations(data, locations, locations_size).await?;
+        }
+
+        // Prune the locations journal to match the data journal if necessary.
+        // We prune data before locations so we should never need to catch data up to locations.
+        match locations.oldest_retained_pos().await? {
+            Some(oldest_retained_pos) if oldest_retained_pos > data_oldest_pos => {
+                // Locations pruned ahead of data → should never happen (violates write ordering)
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: nit: can we remove `→`? I think we should avoid characters that we can't easily type.

If you want to update `AGENTS.md` to indicate, may help for future (same should be said about not using `--` (or however you type the long one)

File: storage/src/journal/contiguous/variable.rs [hunk 8]
```diff
@@ -0,0 +1,1436 @@
...
+            }
+            _ => {
+                // Pruning is consistent
+            }
+        }
+
+        locations.sync().await?;
+        assert_eq!(locations.size().await?, data_size);
+        assert_eq!(
+            locations.oldest_retained_pos().await?,
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: Will this return `None` if it is an empty journal?

I think that may cause an unnecessary assertion failure?

File: storage/src/journal/contiguous/variable.rs (hunk 6 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Yup. If we wrote something into data journal section `N` then we must have synced section `N-1` for the data journal and locations journal section and all sections in `[0, N-1]` are full.

File: storage/src/journal/contiguous/variable.rs (hunk 7 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Do you mean an em dash (—) ?

Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: I removed the arrows. I don't think I have any em dashes in this PR -- did you see some?

File: storage/src/journal/contiguous/variable.rs (hunk 6 above)
Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs]: Can you add a comment explaining as much?

File: storage/src/journal/contiguous/variable.rs (hunk 7 above)
Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs]: Yeah, I was referring to em dash. Didn't see any in the PR was just thinking they'd both be a good addition to the AGENTS.md file 👍

File: storage/src/journal/contiguous/variable.rs (hunk 5 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Suppose we were to prune locations first:

If we crash after deleting the locations journal sections, but before deleting the corresponding sections in the data journal, then on reboot we will find that we have data in the data journal for which we don't have a corresponding entry in the locations journal.

What to do? Assuming we want to keep the invariant that the data journal is the source of truth, then we should repair the locations journal by re-adding the deleted sections.

The locations journal is a `fixed::Journal` which doesn't have prepend functionality so this would be non-trivial.

By pruning the data journal first, we avoid this.

File: storage/src/journal/contiguous/variable.rs (hunk 8 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: In general, no, because at the top of this method we handle the case where the data journal is empty.

However, there is a bug here, which is that we're not handling the case where we crash after opening a section but before writing anything to it. This assertion will only fail if that occurs. I'll add handling for recovering from this crash scenario.

File: storage/src/journal/contiguous/variable.rs (hunk 6 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Added comment on size calculation below

File: storage/src/journal/contiguous/variable.rs (hunk 7 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: PR to update AGENTS.md: https://github.com/commonwarexyz/monorepo/pull/1939

File: storage/src/journal/contiguous/variable.rs (hunk 8 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Added handling for this ^

File: storage/src/journal/contiguous/variable.rs [hunk 9]
```diff
@@ -497,22 +497,43 @@ impl<E: Storage + Metrics, V: Codec + Send> Variable<E, V> {
...
+            }
+            None => None,
+        };
+
+        // Data journal is empty if there are no sections or if there is one section and it has no items.
+        // The latter should only occur if a crash occured after opening a data journal blob but
+        // before writing to it.
+        let data_empty =
+            data.blobs.is_empty() || (data.blobs.len() == 1 && items_in_last_section == Some(0));
+
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: nit: remove `\n`

File: storage/src/journal/contiguous/variable.rs [hunk 10]
```diff
@@ -497,22 +497,43 @@ impl<E: Storage + Metrics, V: Codec + Send> Variable<E, V> {
...
+                let stream = data.replay(*last_section, 0, REPLAY_BUFFER_SIZE).await?;
+                futures::pin_mut!(stream);
+                let mut count = 0u64;
+                while let Some(result) = stream.next().await {
+                    result?; // Propagate replay errors (corruption, etc.)
+                    count += 1;
+                }
+                Some(count)
+            }
+            None => None,
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: We could return 0 here: we never use the fact that `items_in_last_section` can be `None`?

File: storage/src/journal/contiguous/variable.rs (hunk 8 above)
Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs]: Ah, interesting. Missed that.

File: storage/src/journal/contiguous/fixed.rs [hunk 11]
```diff
@@ -0,0 +1,91 @@
+//! Contiguous trait implementation for fixed-length journals.
+
+use super::Contiguous;
+use crate::journal::{fixed, Error};
+use commonware_codec::CodecFixed;
+use commonware_runtime::{Metrics, Storage};
+use futures::Stream;
+use std::num::NonZeroUsize;
+
+impl<E: Storage + Metrics, A: CodecFixed<Cfg = ()> + Send + Sync> Contiguous
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/fixed.rs:10]: I think we should rename this trait `Journal`, move `journal::fixed` here, and rename `journal::variable` to be `XXX` (maybe `log`?).

Comment (patrick-ogrady) [reply storage/src/journal/contiguous/fixed.rs:10]: If we ship as-is, I think we are in effect "shipping our tech debt" (there should not exist a non-contiguous journal)?

Comment (patrick-ogrady) [reply storage/src/journal/contiguous/fixed.rs:10]: I suppose the simplest tweak would be to just rename `journal::variable` to `multijournal` or something...

File: storage/src/journal/mod.rs [hunk 12]
```diff
@@ -64,4 +65,8 @@ pub enum Error {
     CompressionFailed,
     #[error("decompression failed")]
     DecompressionFailed,
+    #[error("corruption detected: {0}")]
+    Corruption(String),
+    #[error("invalid configuration: {0}")]
+    InvalidConfiguration(String),
```
Comment (patrick-ogrady) [inline storage/src/journal/mod.rs:71]: Elsewhere, we assert on this?

Comment (patrick-ogrady) [reply storage/src/journal/mod.rs:71]: https://github.com/commonwarexyz/monorepo/blob/9346bf71ef9a0cd6777bc75f74e1fd55a704e15e/consensus/src/simplex/config.rs#L116-L169

File: storage/src/journal/contiguous/variable.rs (hunk 5 above)
Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs]: Thanks for the clarification.

File: storage/src/journal/contiguous/variable.rs [hunk 13]
```diff
@@ -0,0 +1,1455 @@
...
+    /// appending the missing entries to the locations journal.
+    ///
+    /// The data journal is the source of truth. This function brings the locations
+    /// journal up to date by replaying data items and indexing their positions.
+    ///
+    /// # Invariants
+    ///
+    /// - `data.blobs` must not be empty (data journal has at least one section)
+    /// - `locations_size < data.size()` (locations is behind data)
+    async fn add_missing_locations(
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: LLMs don't like this function:

```
• Review comment:

  - [P0] Fix rebuilding of truncated locations journal — storage/src/journal/contiguous/variable.rs:662-688
    When add_missing_locations runs with an empty locations journal we always start appending at position 0 (see the locations.append(...) loop). If the data journal has previously pruned sections so that data_oldest_pos > 0 (e.g. append 40 items, prune to 20, delete only the locations partition), the rebuild will emit entries for the retained items at logical positions 0..N. data_size
  is still 40, so after the loop locations.size() is 20 and the final assert_eq!(locations.size().await?, data_size) will panic. Even if that assertion were removed the very next append would panic because the rebuilt index is now misaligned with self.size (locations returns 20 while self.size is 40). We need to advance the locations journal to data_oldest_pos before replaying data (or
  otherwise account for the missing prefix) so that the rebuilt index matches the true positions. Until that is fixed we cannot recover from the very scenario this code is meant to handle (loss of the locations partition after pruning).
```

File: storage/src/journal/mod.rs (hunk 12 above)
Comment (danlaine) [reply storage/src/journal/mod.rs:71]: > Elsewhere, we assert on this?

I feel like panicking due to an invalid config is kind of unnecessary. Even if we removed this error value and replaced it with an assertion, `init` would still return a `Result`. So I'm not sure that changing this to an assertion really buys us anything. Wouldn't it be nicer to bubble up the error and let the caller gracefully shut down / recover the program?

File: storage/src/journal/contiguous/variable.rs (hunk 13 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: This scenario can only happen if someone deletes the locations journal partition between runs. It won't happen due to a crash fault.

That said, we _do_ have the data required to repair this fault and there are other places we handle recovery from unexpected (but recoverable) states. I'll add handling for this case, too.

Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs]: I think it is sufficient to only handle faults by our code 🤷

Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Updated the code to detect the case that the LLM identified and return `Error::Corruption`

File: storage/src/journal/contiguous/fixed.rs (hunk 11 above)
Comment (danlaine) [reply storage/src/journal/contiguous/fixed.rs:10]: I'll make a follow-up PR for these renamings

File: storage/src/journal/contiguous/mod.rs [hunk 14]
```diff
@@ -0,0 +1,143 @@
...
+
+// Re-export public types
+pub use variable::{Config, Variable};
+
+#[cfg(test)]
+pub(super) mod tests;
+
+/// Core trait for contiguous journals supporting sequential append operations.
+///
+/// A contiguous journal maintains a monotonically increasing position counter where each
```
Comment (roberto-bayardo) [inline storage/src/journal/contiguous/mod.rs]: Is it only monotonic or is it "consecutively increasing" (no gaps)?

File: storage/src/journal/contiguous/mod.rs [hunk 15]
```diff
@@ -0,0 +1,143 @@
...
+        &self,
+    ) -> impl std::future::Future<Output = Result<Option<u64>, Error>> + Send;
+
+    /// Prune items at positions strictly less than `min_position`.
+    ///
+    /// Returns `true` if any data was pruned, `false` otherwise.
+    ///
+    /// # Behavior
+    ///
+    /// - If `min_position > size()`, the prune is capped to `size()` (no error is returned)
```
Comment (roberto-bayardo) [inline storage/src/journal/contiguous/mod.rs:68]: Should we document the atomicity property here? (e.g. that it's not atomic, but if it fails, there won't be gaps left)?

File: storage/src/journal/contiguous/variable.rs [hunk 16]
```diff
@@ -0,0 +1,1463 @@
...
+        let location = self.locations.read(position).await?;
+
+        // Read item from data journal using the location
+        self.data.get(location.section, location.offset).await
+    }
+
+    /// Sync all pending writes to storage.
+    ///
+    /// This syncs both the data journal and the locations journal.
+    pub async fn sync(&mut self) -> Result<(), Error> {
```
Comment (roberto-bayardo) [inline storage/src/journal/contiguous/variable.rs:420]: If I understand this right, this will result in a performance regression for the variable dbs, since we can no longer sync the log independently from the locations struct (which can be rebuilt from the log if necessary).  Can we introduce a "commit" or similar that only syncs the log?

File: storage/src/journal/contiguous/variable.rs [hunk 17]
```diff
@@ -0,0 +1,1463 @@
...
+            expected_section
+        );
+    }
+
+    /// Test that complete locations partition loss after pruning is detected as unrecoverable.
+    ///
+    /// When the locations partition is completely lost and the data has been pruned, we cannot
+    /// rebuild the index with correct position alignment (would require creating placeholder blobs).
+    /// This is a genuine external failure that should be detected and reported clearly.
+    #[test]
```
Comment (roberto-bayardo) [inline storage/src/journal/contiguous/variable.rs]: did you want to use test_traced instead? (since our journals do a lot of logging...)

File: storage/src/journal/contiguous/mod.rs (hunk 14 above)
Comment (danlaine) [reply storage/src/journal/contiguous/mod.rs]: Changed "monotonic" to "consecutive" in this module

File: storage/src/journal/contiguous/mod.rs (hunk 15 above)
Comment (danlaine) [reply storage/src/journal/contiguous/mod.rs:68]: Added this:

```
/// - This operation is not atomic, but implementations guarantee the journal is left in a
///   recoverable state if a crash occurs during pruning
```

File: storage/src/journal/contiguous/variable.rs (hunk 16 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs:420]: Added a method `sync_data` to this type. I didn't add it to `Contiguous` since that feels like an abstraction break -- that trait doesn't have a notion of data journal vs a locations journal. I think that's fine since I anticipate we'll use this type rather than the `Contiguous` trait for databases that need a contiguous variable journal.

File: storage/src/journal/contiguous/variable.rs (hunk 17 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Changed tests to test_traced

**Review by roberto-bayardo — APPROVED** [review]
New recovery logic looks good!

File: storage/src/journal/contiguous/fixed.rs (hunk 11 above)
Comment (patrick-ogrady) [reply storage/src/journal/contiguous/fixed.rs:10]: Related: #1947

File: storage/src/journal/contiguous/mod.rs [hunk 18]
```diff
@@ -0,0 +1,146 @@
+//! A contiguous journal interface for position-based append-only logging.
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/mod.rs]: nit: `//! An interface for journaling with position-indexed reads.`

File: storage/src/journal/contiguous/mod.rs [hunk 19]
```diff
@@ -0,0 +1,146 @@
...
+//!
+//! This module includes:
+//!
+//! - [Contiguous]: Trait for append-only log
+//! - [Variable]: Wrapper for [super::variable::Journal] that implements [Contiguous]
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/mod.rs:6]: nit: `[Fixed]: ...`

File: storage/src/journal/mod.rs (hunk 12 above)
Comment (patrick-ogrady) [reply storage/src/journal/mod.rs:71]: I won't hold up this PR on this but created an issue to better align: https://github.com/commonwarexyz/monorepo/issues/1982

File: storage/src/journal/contiguous/variable.rs [hunk 20]
```diff
@@ -0,0 +1,1477 @@
...
+};
+use tracing::info;
+
+const REPLAY_BUFFER_SIZE: NonZeroUsize = NZUsize!(1024);
+
+/// Location of an item in the variable journal.
+#[derive(Debug, Clone, Copy, PartialEq, Eq)]
+struct Location {
+    /// Section number where the item is stored
+    section: u64,
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: If `items_per_section` is provided in config, do we need to store section? I think we can always infer it (we should just need to store offset)?

File: storage/src/journal/contiguous/variable.rs [hunk 21]
```diff
@@ -0,0 +1,1477 @@
...
+/// * `oldest_retained_pos` - The position of the first item after pruning (section-aligned)
+/// * `items_per_section` - The number of items stored in each section
+///
+/// # Returns
+///
+/// The section number where the item at `position` should be stored.
+///
+/// # Examples
+///
+/// ```ignore
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs:39]: nit: prefer `rust` (I don't think `ignore` is checked in CI)?

File: storage/src/journal/contiguous/variable.rs [hunk 22]
```diff
@@ -0,0 +1,1477 @@
...
+    /// Write buffer size for each section.
+    pub write_buffer: NonZeroUsize,
+}
+
+/// A contiguous wrapper around [variable::Journal] that implements an append-only log.
+///
+/// This wrapper manages section assignment automatically, allowing callers to append items
+/// sequentially without manually tracking section numbers.
+///
+/// # Invariants
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs:93]: Very nice

File: storage/src/journal/contiguous/variable.rs [hunk 23]
```diff
@@ -0,0 +1,1477 @@
...
+            return Err(Error::InvalidRewind(size));
+        }
+
+        // Read the location of the first item to discard (at position 'size').
+        let discard_location = self.locations.read(size).await?;
+
+        self.data
+            .rewind_to_offset(discard_location.section, discard_location.offset)
+            .await?;
+        self.locations.rewind(size).await?;
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: The rationale for not needing to `sync` here is that recovery should be able to handle this, right?

File: storage/src/journal/contiguous/variable.rs [hunk 24]
```diff
@@ -0,0 +1,1477 @@
...
+        // Use locations index to find section/offset to start from
+        let location = self.locations.read(start_pos).await?;
+        let data_stream = self
+            .data
+            .replay(location.section, location.offset, buffer_size)
+            .await?;
+
+        // Transform the stream to include position information
+        let transformed = data_stream.enumerate().map(move |(idx, result)| {
+            result.map(|(_section, _offset, _size, item)| {
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs:368]: I'm assuming this handles idx incrementation on `result` failure correctly?

File: storage/src/journal/contiguous/variable.rs [hunk 25]
```diff
@@ -0,0 +1,1477 @@
...
+        }
+        Ok(())
+    }
+
+    /// Sync all pending writes to storage.
+    ///
+    /// This syncs both the data journal and the locations journal.
+    pub async fn sync(&mut self) -> Result<(), Error> {
+        // Sync data journal
+        self.sync_data().await?;
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: nit: I think it is safe to sync concurrently if `data` is the source of truth, no?

That would also allow us to remove the separate sync_data (it should be ~no worse to sync concurrently).

File: storage/src/journal/contiguous/variable.rs [hunk 26]
```diff
@@ -0,0 +1,1477 @@
...
+            }
+            Some(oldest_retained_pos) if oldest_retained_pos > data_oldest_pos => {
+                return Err(Error::Corruption(format!(
+                    "locations oldest pos ({oldest_retained_pos}) > data oldest pos ({data_oldest_pos})"
+                )));
+            }
+            Some(_) => {
+                // Both journals are pruned to the same position.
+            }
+            None if data_oldest_pos > 0 => {
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs:555]: We can hit this case if we never synced locations (shutdown between data.sync() and locations.sync()). I think we need to tolerate it with add_missing_locations?

File: storage/src/journal/contiguous/variable.rs (hunk 23 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Yes we should be able to recover from any crash failure

File: storage/src/journal/contiguous/variable.rs (hunk 24 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs:368]: Could you elaborate? `idx` is coming from `enumerate()` so it should not be affected by the value of `result`

File: storage/src/journal/contiguous/variable.rs (hunk 20 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Changed to only store offset

File: storage/src/journal/contiguous/variable.rs (hunk 21 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs:39]: `position_to_section` is private so this won't pass doc tests:

```
error[E0425]: cannot find function `position_to_section` in this scope
 --> storage/src/journal/contiguous/variable.rs:36:12
  |
4 | assert_eq!(position_to_section(0, 0, 10), 0);   // position 0 -> section 0
  |            ^^^^^^^^^^^^^^^^^^^ not found in this scope
```

File: storage/src/journal/contiguous/variable.rs (hunk 26 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs:555]: Added handling for this case and a regression test

File: storage/src/journal/contiguous/mod.rs (hunk 19 above)
Comment (danlaine) [reply storage/src/journal/contiguous/mod.rs:6]: Added list item for fixed

File: storage/src/journal/contiguous/variable.rs (hunk 25 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: ~~The problem is that we want to avoid syncing the `offsets` (previously `locations`) journal before the `data` journal because of [this issue](https://github.com/commonwarexyz/monorepo/pull/1893#discussion_r2446239459).~~

Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Hmm actually I don't think this matters for pruning because `prune` calls `remove_blob` so it shouldn't matter if we later call `sync` on the offsets journal first.

Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Changed this to be concurrent and removed `sync_data`

CC @roberto-bayardo who requested that I add `sync_data`, in case he feels strongly it should be kept

Comment (roberto-bayardo) [reply storage/src/journal/contiguous/variable.rs]: Yeah this is going to cause performance regressions in our adbs...  we want to be able to sync only the log on "commit".  Even when running them concurrently.

File: storage/src/journal/contiguous/variable.rs (hunk 24 above)
Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs:368]: I misread. Disregard.

File: storage/src/journal/contiguous/variable.rs [hunk 27]
```diff
@@ -0,0 +1,1507 @@
...
+        let offsets_pos = self.offsets.append(offset).await?;
+        assert_eq!(offsets_pos, self.size);
+
+        // Return the current position
+        let position = self.size;
+        self.size += 1;
+
+        // Maintain invariant that all full sections are synced.
+        if self.size.is_multiple_of(self.items_per_section) {
+            self.data.sync(section).await?;
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: nit: this can be synced concurrently?

Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Done

File: storage/src/journal/contiguous/variable.rs (hunk 25 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Re-added `sync_data`.

File: storage/src/journal/contiguous/variable.rs [hunk 28]
```diff
@@ -0,0 +1,1519 @@
...
+            if let Some(oldest) = offsets.oldest_retained_pos().await? {
+                if oldest < size {
+                    // Offsets has unpruned entries but data is gone - repair by pruning
+                    info!("crash repair: pruning offsets to {size} (prune-all crash)");
+                    offsets.prune(size).await?;
+                    offsets.sync().await?;
+                }
+            }
+
+            return Ok((size, size));
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs:517]: If I'm not mistaken, it is possible that the `size` returned as the first item here isn't section-aligned?

Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs:517]: Not sure if this is a problem if the invariant "all sections other than last are full" is meant to be upheld?

Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs:517]: I think this could particularly affect the correctness of `position_to_section`

File: storage/src/journal/contiguous/variable.rs [hunk 29]
```diff
@@ -0,0 +1,1519 @@
...
+/// assert_eq!(position_to_section(25, 0, 10), 2);  // position 25 -> section 2
+///
+/// // After pruning sections 0-1 (oldest_retained_pos = 20):
+/// assert_eq!(position_to_section(20, 20, 10), 2); // position 20 -> section 2
+/// assert_eq!(position_to_section(25, 20, 10), 2); // position 25 -> section 2
+/// assert_eq!(position_to_section(30, 20, 10), 3); // position 30 -> section 3
+/// ```
+const fn position_to_section(
+    position: u64,
+    oldest_retained_pos: u64,
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: should we assert this is section aligned?

File: storage/src/journal/contiguous/variable.rs [hunk 30]
```diff
@@ -0,0 +1,1519 @@
...
+    pub async fn prune(&mut self, min_position: u64) -> Result<bool, Error> {
+        if min_position <= self.oldest_retained_pos {
+            return Ok(false);
+        }
+
+        // Cap min_position to size to maintain the invariant oldest_retained_pos <= size
+        let min_position = min_position.min(self.size);
+
+        // Calculate section number
+        let min_section = min_position / self.items_per_section;
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs]: Do we need to do position_to_section here?

File: storage/src/journal/contiguous/variable.rs (hunk 28 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs:517]: `data.blobs.is_empty()` holds which means either:

1. This journal never contained anything
2. This journal was fully pruned

In case (1), offsets journal must also have size 0. We return (0,0) and that's fine.

In case (2):
* If offsets journal has size 0, then we return (0,0) and that's fine.
* If offsets journal has size > 0, we need that `size` is section-aligned. Does that hold?

Consider the state of the journal just before it was pruned. The data journal must have been section-aligned because after we pruned it, it was completely empty, and we prune on a per-section basis. If the data journal's size was section-aligned, then the offsets journal must have been section-aligned too.

Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs:517]: > then the offsets journal must have been section-aligned too.

Still convincing myself of this.

Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs:517]: >The data journal must have been section-aligned because after we pruned it, it was completely empty, and we prune on a per-section basis.

Isn't it possible we provided a min_position >> last position (where min_position is in the next section)?

File: storage/src/journal/contiguous/variable.rs (hunk 29 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: added assertion

File: storage/src/journal/contiguous/variable.rs (hunk 28 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs:517]: > Isn't it possible we provided a min_position >> last position (where min_position is in the next section)?

Hmm yeah I wasn't accounting for that. So the offsets journal isn't necessarily section-aligned.

So, what do? We could:

1. In recovery, round `size` up to the nearest section-aligned value if it isn't section-aligned (i.e. this situation occurred -- we pruned the entire journal AND the last section wasn't full when we pruned).
2. Change `prune` to not allow pruning away entries which haven't been set (makes it true that, if we pruned away the entire data journal, then the offset journal size must be section-aligned.)

Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs:517]: https://github.com/commonwarexyz/monorepo/pull/1986

Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs:517]: will ponder best route, I kinda think I could see myself doing [2] so lean [1]

File: storage/src/journal/contiguous/variable.rs (hunk 30 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs]: Changed to use `position_to_section` (and simplify unnecessarily complicated logic in that function)

File: storage/src/journal/contiguous/variable.rs (hunk 28 above)
Comment (danlaine) [reply storage/src/journal/contiguous/variable.rs:517]: Wait actually we don't allow pruning away a section that isn't full

File: storage/src/journal/contiguous/variable.rs [hunk 31]
```diff
@@ -0,0 +1,1440 @@
...
+                offsets.rewind(target_pos).await?;
+                offsets.sync().await?;
+                return Ok((target_pos, target_pos));
+            }
+
+            // data.blobs is empty. This can happen in two cases:
+            // 1. We completely pruned the data journal but crashed before pruning
+            //    the offsets journal.
+            // 2. The data journal was never opened.
+            if let Some(oldest) = offsets.oldest_retained_pos().await? {
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs:508]: dumb solution: if `data` is truly non-existent, let's just blow away offsets?

File: storage/src/journal/contiguous/variable.rs (hunk 28 above)
Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs:517]: I think the most robust fix (mentioned in the linked PR) is to just make sure the last item is never pruned!

File: storage/src/journal/contiguous/variable.rs [hunk 32]
```diff
@@ -0,0 +1,1409 @@
...
+            Some(_) => {
+                // Both journals are pruned to the same position.
+            }
+            None if data_oldest_pos > 0 => {
+                // Offsets journal is empty (size == oldest_retained_pos).
+                // This can happen if we pruned all data, then appended new data, synced the
+                // data journal, but crashed before syncing the offsets journal.
+                // We can recover if offsets.size() matches data_oldest_pos (proper pruning).
+                let offsets_size = offsets.size().await?;
+                if offsets_size != data_oldest_pos {
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs:561]: idk why the intuition around this logic escaped me a few days ago but I now "get it" (we only allow the pruning to get "one sync ahead" or else consider it corrupt)

File: storage/src/journal/contiguous/variable.rs [hunk 33]
```diff
@@ -184,6 +184,10 @@ impl<E: Storage + Metrics, V: Codec + Send> Variable<E, V> {
         // Validate and repair offsets journal to match data journal
         let (oldest_retained_pos, size) =
             Self::repair_journals(&mut data, &mut offsets, items_per_section).await?;
+        assert!(
```
Comment (patrick-ogrady) [inline storage/src/journal/contiguous/variable.rs:187]: I thought we added this `assert!` already (but it may have been in a branch or something)

Comment (patrick-ogrady) [reply storage/src/journal/contiguous/variable.rs:187]: Ah, yep was in #1986
