### PR TITLE
Ensures the runtime cleans up tasks before panicking due to a timeout.

### LINKED ISSUE #2136: [runtime/deterministic] Avoid Double Panic on Runtime Timeout
When the [runtime times out](https://github.com/commonwarexyz/monorepo/blob/554fd5adca87404903326b20a95d8893c038e2f8/runtime/src/deterministic.rs#L457), it will begin unwinding and free the `Executor`. There are still references to the `Executor`, however, so this leads to a second panic on [`.upgrade()` failing](https://github.com/commonwarexyz/monorepo/blob/554fd5adca87404903326b20a95d8893c038e2f8/runtime/src/deterministic.rs#L903).

### PR DESCRIPTION
**Pull request by evonide**
Fixes #2136 in a concise way.

I had trouble writing a test which can reproduce this outside of observed fuzzing crashes. Please note that a double panic results in an immediate abort so I'm not sure to which extent a test is feasible to begin with.

### CODE REVIEW

File: runtime/src/deterministic.rs [hunk 1]
```diff
@@ -591,6 +597,9 @@ impl Runner {
             catch_panics: executor.panicker.catch(),
         };
 
+        // Panic after the cleanup if a timeout has occurred.
+        let output = output.expect("runtime timeout");
```
Comment (patrick-ogrady) [inline runtime/src/deterministic.rs]: Seems we could expect this after the weak_count assert?

**Comment by patrick-ogrady** [comment]
> Please note that a double panic results in an immediate abort so I'm not sure to which extent a test is feasible to begin with.

Tough to test we went from double to single panic lol
