### PR TITLE
[p2p] Release sends message to `tracker` rather than `directory`

### LINKED ISSUE #1106: [p2p] Release/Connect race-condition results in panic
Sometimes a panic can be encountered:
```
p2p/src/authenticated/actors/tracker/record.rs:173:9:assertion failed: matches!(self.status, Status::Reserved)
```

This seems to be due to a race condition between `Connect` and a reservation being dropped (releasing the reservation). This is because the reservation being dropped does not enter the same message queue as the connect message.

Reservations being dropped are processed [here](https://github.com/commonwarexyz/monorepo/blob/61e13881254fe7e97ed95e06831a61f565b812bc/p2p/src/authenticated/actors/tracker/actor.rs#L139), which superceeds any `Connect` messages for the same peer. Thus, if the peer has sent a `Connect` message to the tracker (upon initialization of the connection), but the connection is killed before this `Connect` message is processed by the tracker, then the reservation dropped by the killed connection will be processed before the `Connect` message, resulting in this panic. Classic race condition

### PR DESCRIPTION
**Pull request by BrendanChou**
Fixes #1106 

Unfortunately I found it hard to create a test for this issue (to prevent regression) due to how the runtime deals with async stuff and how you have to release the reservation AFTER connecting, but also immediately, but then also during that time never loop a single time within the tracker actor

### CODE REVIEW

File: p2p/src/authenticated/actors/tracker/actor.rs [hunk 1]
```diff
@@ -136,7 +148,6 @@ impl<E: Spawner + Rng + Clock + GClock + RuntimeMetrics, C: Signer> Actor<E, C>
 
     async fn run(mut self) {
         while let Some(msg) = self.receiver.next().await {
-            self.directory.process_releases();
```
Comment (patrick-ogrady) [inline p2p/src/authenticated/actors/tracker/actor.rs:139]: I suppose another fix, albeit probably more confusing, would be to remove the `assert!` in `record.rs`: https://github.com/commonwarexyz/monorepo/blob/c46312f8af42edb7bbeefc1bd8c0216eaff871f3/p2p/src/authenticated/actors/tracker/record.rs#L169-L175

Comment (patrick-ogrady) [reply p2p/src/authenticated/actors/tracker/actor.rs:139]: (I like that we respect a strict state model there fwiw)

File: p2p/src/authenticated/actors/tracker/actor.rs [hunk 2]
```diff
@@ -229,6 +240,10 @@ impl<E: Spawner + Rng + Clock + GClock + RuntimeMetrics, C: Signer> Actor<E, C>
                     // We don't have to kill the peer now. It will be sent a `Kill` message the next
                     // time it sends the `Connect` or `Construct` message to the tracker.
                 }
+                Message::Release { metadata } => {
```
Comment (patrick-ogrady) [inline p2p/src/authenticated/actors/tracker/actor.rs:243]: To make the importance of this `connect` before `release` ordering more explicit, I'm wondering if we should move this line to be the first thing we do in `peer::run`: https://github.com/commonwarexyz/monorepo/blob/c46312f8af42edb7bbeefc1bd8c0216eaff871f3/p2p/src/authenticated/actors/peer/actor.rs#L129-L130

File: p2p/src/authenticated/actors/tracker/actor.rs
Comment (patrick-ogrady) [inline p2p/src/authenticated/actors/tracker/actor.rs:1]: Was going to suggest another approach may be to only use the `Inert` and `Reserved` statuses but like the different behavior we take based on being actually connected to the peer. (Not a good suggestion, just boiling the ocean).

File: p2p/src/authenticated/actors/tracker/actor.rs (hunk 2 above)
Comment (patrick-ogrady) [reply p2p/src/authenticated/actors/tracker/actor.rs:243]: May also be worth commenting this invariant explicitly (that `Connect` must be sent before reserved), if we don't just ignore in that case...which seems a bit of a "cop out" admittedly.

File: p2p/src/authenticated/actors/tracker/reservation.rs [hunk 3]
```diff
@@ -39,26 +38,22 @@ impl<E: Spawner + Metrics, P: PublicKey> Reservation<E, P> {
...
     fn drop(&mut self) {
-        let mut closer = self.closer.take().expect("Reservation::drop called twice");
+        let mut releaser = self
+            .releaser
+            .take()
+            .expect("Reservation::drop called twice");
 
         // If the mailbox is not full, we can release the reservation immediately without spawning a task.
-        let Err(e) = closer.try_send(self.metadata.clone()) else {
+        if releaser.try_release(self.metadata.clone()) {
```
Comment (patrick-ogrady) [inline p2p/src/authenticated/actors/tracker/reservation.rs:47]: Thanks for the cleanup 🙏

**Review by patrick-ogrady — COMMENTED** [review]
Left some minor comments on different (bad) approaches and a suggestion to make the `Connect before Drop` more explicit.

File: p2p/src/authenticated/actors/tracker/ingress.rs [hunk 4]
```diff
@@ -187,6 +197,44 @@ impl<E: Spawner + Metrics, C: PublicKey> Mailbox<E, C> {
...
+            e.is_full(),
+            "Unexpected error trying to release reservation {:?}",
+            e
+        );
+        false
+    }
+
+    /// Release a reservation.
+    ///
+    /// This method will panic if the mailbox is full.
```
Comment (danlaine) [inline p2p/src/authenticated/actors/tracker/ingress.rs]: Is this true? If `self.sender` is full, won't we just block here until there is space?

File: p2p/src/authenticated/actors/tracker/reservation.rs [hunk 5]
```diff
@@ -39,26 +38,22 @@ impl<E: Spawner + Metrics, P: PublicKey> Reservation<E, P> {
...
-            });
-        } else {
-            // If any other error occurs, we should panic!
-            panic!(
-                "unexpected error while trying to release reservation: {:?}",
-                e
-            );
-        }
+
+        // If the mailbox is full, we need to spawn a task to handle the release. If we used `block_on` here,
```
Comment (danlaine) [inline p2p/src/authenticated/actors/tracker/reservation.rs]: Would we actually deadlock here if we were to wait until we can send the release message? I think that as long as the tracker can still make progress (i.e. drain items from its `receiver`) then `drop` should eventually return. Is there a case where the tracker can't make progress until `drop` completed?

File: p2p/src/authenticated/actors/tracker/actor.rs (hunk 1 above)
Comment (patrick-ogrady) [reply p2p/src/authenticated/actors/tracker/actor.rs:139]: After sleeping on this, I'm now wondering if removing these asserts is also a good idea (and just dropping things that don't make sense).

File: p2p/src/authenticated/actors/tracker/reservation.rs (hunk 3 above)
Comment (BrendanChou) [reply p2p/src/authenticated/actors/tracker/reservation.rs:47]: It was a cleanup of a change (i.e. mess) that I made 😅

File: p2p/src/authenticated/actors/tracker/actor.rs (hunk 2 above)
Comment (BrendanChou) [reply p2p/src/authenticated/actors/tracker/actor.rs:243]: To clarify, we don't need to `connect` before `release`; a `release` without a `connect` is just fine. We just need to make sure we don't `connect` after `release`.

File: p2p/src/authenticated/actors/tracker/actor.rs (hunk 1 above)
Comment (patrick-ogrady) [reply p2p/src/authenticated/actors/tracker/actor.rs:139]: Related: #1110
