### PR TITLE
[stream] Add explicit key-confirmation to handshake

### LINKED ISSUE #1018: [stream] Prevent handshake replay
A random unique challenge is not used to protect against a replay attack, and the protocol relies on a timestamp sent in plaintext via a common time reference instead.

Another option is a monotonic counter.

### LINKED ISSUE #1076: [Stream] Lack of explicit key-confirmation in the handshake
The current Stream handshake stops after verifying each peer’s signature and deriving encryption keys from an *ephemeral–ephemeral* DH shared secret.  It does **not** send a final MAC-over-transcript (“Finished” in TLS 1.3 or SIGMA‐style key-confirmation).  As a result, authentication can be maximum only *implicit*: the connection is established and trusted once the key derivation is performed successfully. In implicit key confirmation, the connection is established and trusted once the first ciphertext in each direction is decrypted successfully. Currently, this is not guaranteed to be enforced because ChaCha20-Poly1305 authentication failure in `Receiver::receive()`  is mapped to [`Error::DecryptionFailed`](https://github.com/commonwarexyz/monorepo/blob/2aa10dd4e00bbcc1f993ecccb67e3b4aa4495fb5/stream/src/public_key/connection.rs#L344) and the function returns, but the `Connection` instance may remain alive. Likewise, if the first ciphertext from the peer fails to decrypt, the transport layer signals an error but does not automatically close the channel. Closing, ignoring or re-handshaking is left to the caller.

Impact:
* Leaves a narrow window for transcript-splicing / UKS / KCI corner-cases in the cryptographic protocol and logical bugs in the higher-level protocols that a Finished-style MAC would block.  
* Dialer authentication: The listener can send application data before it has seen proof that the dialer holds the traffic keys (the dialer will not be able to decrypt the data, but the listener will be sure that the data was sent) 
* Listener authentication: The unauthenticated listener can send application data before it has been verified by the dialer. We can think about DoS attack against the dialer.  
* It is harder to define the boundary when the party has been explicitly authenticated.
* The user can degrade the security of the protocol by using its primitives incorrectly

Options:

- Add explicit key-confirmation: one more field with MAC; dialer can start sending data immediately after checking that MAC, but the listener will not be able to start sending data until it receives a Finished message with traffic from the dialer
- Still use implicit confirmation, but immediately close the connection and remove the peer if the first message with data can't be decrypted, and do not allow the user of the Stream to control it

### PR DESCRIPTION
**Pull request by BrendanChou**
Fixes #1076 
Fixes #1018 by not letting a "spoofing" party keep the connection open longer than the handshake timeout (see https://github.com/commonwarexyz/monorepo/pull/1132#discussion_r2158034085)

TODO:
- [x] Rename `AuthenticationProof` as `KeyConfirmation`
  - [x] See if there's a good way to simplify this type as well, and have it implement `FixedSize`
- [x] Update documentation to reflect the new behavior
- [x] Ensure tests look good and have full coverage

### CODE REVIEW

File: stream/src/public_key/connection.rs [hunk 1]
```diff
@@ -192,26 +205,55 @@ impl<Si: Sink, St: Stream> Connection<Si, St> {
...
+            nonce_recv: l2d_nonce,
         })
     }
 
     /// Attempt to upgrade a connection initiated by some peer.
     ///
-    /// Because we already verified the peer's handshake, this function
-    /// only needs to send our handshake message for the connection to be fully
-    /// initialized.
+    /// This implements the 3-message handshake protocol where the listener:
```
Comment (patrick-ogrady) [inline stream/src/public_key/connection.rs:252]: The rationale for not doing this originally was/is that it allows an adversary to hold many connections open at one (stuck in this handshake phase).

That being said, this prevents a dialer with a valid initial handshake from a peer (which would require connection snooping) from preventing the actual peer from acquiring a tracker reservation.

I'm not yet sold that this is something we should worry about in our threat model. If we do, however, what you have is very very close to what I'd suggest.

This may also allow us to avoid replay protections in p2p.

Comment (patrick-ogrady) [reply stream/src/public_key/connection.rs:252]: I suppose doing this all in the initial handshake doesn't make it any "worse" 🤔

File: stream/src/public_key/connection.rs [hunk 2]
```diff
@@ -192,26 +205,55 @@ impl<Si: Sink, St: Stream> Connection<Si, St> {
...
             shared_secret.as_bytes(),
             &[&config.namespace, &d2l_msg, &l2d_msg],
         )?;
 
-        // We keep track of dialer to determine who adds a bit to their nonce (to prevent reuse)
+        // Create nonce counters for each direction (starting at 0)
+        let mut d2l_nonce = nonce::Info::default();
+        let mut l2d_nonce = nonce::Info::default();
+
+        // Verify listener's authentication proof (uses nonce 0)
```
Comment (dnkolegov-ar) [inline stream/src/public_key/connection.rs]: My suggestion is to derive a separate pair of keys and use distinct nonces for each as described in https://datatracker.ietf.org/doc/html/rfc8446#section-4.4.4. We have already had for that. We just need to use HKDF-Expand with different `Info` for authentication keys and transport keys.

File: stream/src/public_key/handshake.rs [hunk 3]
```diff
@@ -189,6 +194,186 @@ impl<C: PublicKey> EncodeSize for Signed<C> {
     }
 }
 
+/// Proof that a party can correctly derive the shared secret.
```
Comment (dnkolegov-ar) [inline stream/src/public_key/handshake.rs]: A common and established term for this is "key confirmation". `AuthenticationProof` may be misleading, as the protocol already uses signatures for authentication.

File: stream/src/public_key/connection.rs (hunk 1 above)
Comment (BrendanChou) [reply stream/src/public_key/connection.rs:252]: - Yes! Doing it in the handshake doesn't make it any worse since it uses the original timeout. In both cases (the dialer and the listener), the handshake timeout only has to be long enough for the parties to each send a single message, so this shouldn't increase the length of what we set the handshake timeout to be.
- And yes I think this could also solve #1018 in a roundabout way; while it doesn't prevent replay attacks on the handshake data itself, the key-confirmation step uses a call/response pattern that prevents replay attacks.

File: stream/src/public_key/connection.rs (hunk 2 above)
Comment (BrendanChou) [reply stream/src/public_key/connection.rs]: What you mention is just "standard" practice right? Is there any direct reason why simply using `nonce: 0` in ChaCha20Poly1305 for the key confirmation would be bad?

I prefer whatever results in the easiest-to-understand/maintain code if it's equivalently secure.

File: stream/src/public_key/handshake.rs (hunk 3 above)
Comment (BrendanChou) [reply stream/src/public_key/handshake.rs]: Great will fix this in the next pass

File: stream/src/public_key/connection.rs (hunk 1 above)
Comment (BrendanChou) [reply stream/src/public_key/connection.rs:252]: > what you have is very very close to what I'd suggest

Anything specific you want to change? I considered having the `listener` send the messages (response handshake, key confirmation) as two different framed messages, but ended up just putting them together into one. Two messages wouldn't require an extra round-trip; it could just fire both off at the same time.

File: stream/src/public_key/connection.rs (hunk 2 above)
Comment (dnkolegov-ar) [reply stream/src/public_key/connection.rs]: At least because you need to remember why you can't use that nonce anymore. In the second approach, you derive new keys and then you do not need to care about nonces anymore.

**Comment by dnkolegov-ar** [comment]
> Update documentation to reflect the new behavior

I was also thinking about describing the protocol in a more cryptographic way (in the same style as WireGuard), as it has become more complex than its initial version. Should we do that together in the same next PR?

File: stream/src/public_key/connection.rs (hunk 1 above)
Comment (dnkolegov-ar) [reply stream/src/public_key/connection.rs:252]: > while it doesn't prevent replay attacks on the handshake data itself, the key-confirmation step uses a call/response pattern that prevents replay attacks.

I did not get it. So, in your opinion, does it prevent or not prevent replay attacks?

Comment (BrendanChou) [reply stream/src/public_key/connection.rs:252]: Overall it does have the effect of preventing replay attacks.

It cannot prevent "pre-play" attacks where the attacker sniffs the dialers handshake and uses it before the valid dialer itself can. But I'd argue that nothing can stop that attack.

It does prevent the re-use of listener handshakes since it is now coupled with the key-confirmation.

It does not technically prevent re-use of the dialer handshake once it has been used. However, this is not a large issue as 1) the legitimate actor would have had to already disconnect within a very short period of time (due to the validity time on the timestamp of the handshake) and 2) the attacker would not be able to complete the second part of the dialer handshake, preventing them from holding the connection open longer than the handshake timeout. In fact, in most setups replay would be prevented by the combination of rate-limiting and the synchrony bound on the handshake timestamp anyway.

File: stream/src/public_key/handshake.rs [hunk 4]
```diff
@@ -189,6 +191,178 @@ impl<C: PublicKey> EncodeSize for Signed<C> {
...
+
+impl KeyConfirmation {
+    /// Create a new key confirmation using the provided cipher and ephemeral public key.
+    ///
+    /// The confirmation encrypts the ephemeral public key of the peer to demonstrate
+    /// knowledge of the shared secret in a challenge-response fashion.
+    pub fn create(
+        cipher: &ChaCha20Poly1305,
+        nonce: &Nonce,
+        ephemeral_key: &x25519::PublicKey,
```
Comment (dnkolegov-ar) [inline stream/src/public_key/handshake.rs]: The suggestion is to use the transcript hash instead of the ephemeral public key. Shared the design.

File: stream/src/public_key/handshake.rs [hunk 5]
```diff
@@ -189,6 +191,178 @@ impl<C: PublicKey> EncodeSize for Signed<C> {
...
+    ) -> Result<Self, Error> {
+        // Encrypt the confirmation
+        let encrypted_proof = cipher
+            .encrypt(nonce, ephemeral_key.encode().as_ref())
```
Comment (dnkolegov-ar) [inline stream/src/public_key/handshake.rs]: We do not need encryption here: it should be HMAC or AEAD tag

File: stream/src/public_key/connection.rs (hunk 2 above)
Comment (BrendanChou) [reply stream/src/public_key/connection.rs]: I think this is a reasonable take. I would argue that we already have this exact problem (you can't reuse a nonce) and a tool to solve it (`nonce::Info`), therefore re-using this tool probably introduces the least complexity and new code paths (at least in this particular case). I could see how simply generating additional keys in the expand step could be simpler in many instances. I'll take a look at implementing that as a one-off to see how it makes the code look

File: stream/src/public_key/cipher.rs [hunk 6]
```diff
@@ -10,23 +10,62 @@ const CHACHA_KEY_SIZE: usize = <ChaCha20Poly1305 as KeySizeUser>::KeySize::USIZE
 // A constant prefix used for the salt hash in the HKDF key derivation.
 const BASE_KDF_PREFIX: &[u8] = b"commonware-stream/KDF/v1/";
 
-/// Key Derivation Function (KDF) to derive directional ChaCha20Poly1305 ciphers using HKDF-SHA256.
+// Constant infos for directional ciphers.
+const D2L_TRAFFIC_INFO: &[u8] = b"l2d/traffic";
```
Comment (dnkolegov-ar) [inline stream/src/public_key/cipher.rs]: Should we use the following? Just to not misuse  L2D_TRAFFIC_INFO/L2D_CONFIRMATION_INFO and  D2L_TRAFFIC_INFO/D2L_CONFIRMATION_INFO starting with the same letters in the future?
```
const TRAFFIC_INFO_D2L: &[u8] = b"d2l/traffic";
const TRAFFIC_INFO_L2D: &[u8] = b"l2d/traffic";

const CONFIRM_INFO_D2L: &[u8] = b"d2l/confirmation";
const CONFIRM_INFO_L2D: &[u8] = b"l2d/confirmation";
```

File: stream/src/public_key/mod.rs [hunk 7]
```diff
@@ -64,6 +64,10 @@
 
 use std::time::Duration;
 
+// When encrypting data, an encryption tag is appended to the ciphertext.
+// This constant represents the size of the encryption tag in bytes.
+const ENCRYPTION_TAG_LENGTH: usize = 16;
```
Comment (dnkolegov-ar) [inline stream/src/public_key/mod.rs]: It should be `AUTHENTICATION_TAG` - [link](https://docs.rs/chacha20poly1305/latest/src/chacha20poly1305/lib.rs.html#76)

File: stream/src/public_key/handshake.rs [hunk 8]
```diff
@@ -198,6 +206,114 @@ impl<C: PublicKey> EncodeSize for Signed<C> {
...
+
+impl KeyConfirmation {
+    /// Create a new key confirmation using the provided cipher and handshake transcript.
+    ///
+    /// The confirmation encrypts the handshake transcript to demonstrate
+    /// knowledge of the shared secret and bind the confirmation to the entire handshake exchange.
+    pub fn create(mut cipher: ChaCha20Poly1305, transcript: &[u8]) -> Result<Self, Error> {
+        // Encrypt the confirmation using the transcript as associated data
+        let tag = cipher
+            .encrypt_in_place_detached(&Nonce::default(), transcript, &mut [])
```
Comment (dnkolegov-ar) [inline stream/src/public_key/handshake.rs:230]: Is nonce single-use here guaranteed somehow? If not, we must implement that, because otherwise we will experience nonce reuse. The invariant is that KeyConfirmation::create must be called once per handshake. Correct?

File: stream/src/public_key/connection.rs [hunk 9]
```diff
@@ -191,27 +201,58 @@ impl<Si: Sink, St: Stream> Connection<Si, St> {
...
+            cipher_recv: l2d,
         })
     }
 
     /// Attempt to upgrade a connection initiated by some peer.
     ///
-    /// Because we already verified the peer's handshake, this function
-    /// only needs to send our handshake message for the connection to be fully
-    /// initialized.
+    /// This implements the 3-message handshake protocol where the listener:
```
Comment (dnkolegov-ar) [inline stream/src/public_key/connection.rs:252]: Now we have three messages, but what about RTT? RTT is 1, right? Is it correct that the listener can start sending/receiving data only after getting the confirmation message from the dialer, which can start sending data immediately after sending its confirmation (together with data)?

File: stream/src/public_key/connection.rs (hunk 2 above)
Comment (BrendanChou) [reply stream/src/public_key/connection.rs]: Used multiple HKDF Expands. resolving

File: stream/src/public_key/mod.rs [hunk 10]
```diff
@@ -11,32 +11,59 @@
...
 //!
+//! ### Message 2: Listener → Dialer (Response with Key Confirmation)
 //! The listener verifies the public keys are well-formatted, the timestamp is valid (not too old/not too far in the future),
 //! and that the signature is valid. If all these checks pass, the listener checks to see if it is already connected or dialing
-//! this peer. If it is, it drops the connection. If it isn't, it sends back its own signed handshake message (same as above)
-//! and considers the connection established.
+//! this peer. If it is, it drops the connection. If it isn't, the listener:
+//!
+//! 1. Creates its own signed handshake message (same format as above)
+//! 2. Derives the shared secret from the ephemeral keys
```
Comment (dnkolegov-ar) [inline stream/src/public_key/mod.rs]:
```suggestion
//! 2. Computes the X25519 Diffie-Hellman shared secret using our newly generated ephemeral private key and the peer’s ephemeral public key.
```

File: stream/src/public_key/mod.rs [hunk 11]
```diff
@@ -11,32 +11,59 @@
...
 //!
 //! In any handshake, the dialer is the party that attempts to connect to some known address/identity (public key)
-//! and the recipient of this connection is the listener. Upon forming a TCP connection, the dialer sends a signed
-//! handshake message to the listener. Besides the signature and the public key of the dialer, the handshake message
-//! contains:
+//! and the recipient of this connection is the listener. The 3-message handshake protocol works as follows:
+//!
+//! ### Message 1: Dialer → Listener (Initial Handshake)
+//! Upon forming a TCP connection, the dialer sends a signed handshake message to the listener.
+//! Besides the signature and the public key of the dialer, the handshake message contains:
```
Comment (dnkolegov-ar) [inline stream/src/public_key/mod.rs]:
```suggestion
//! Besides the signature and the static public key of the dialer, the handshake message contains:
```

File: stream/src/public_key/mod.rs [hunk 12]
```diff
@@ -11,32 +11,59 @@
...
+//! ### Message 2: Listener → Dialer (Response with Key Confirmation)
 //! The listener verifies the public keys are well-formatted, the timestamp is valid (not too old/not too far in the future),
 //! and that the signature is valid. If all these checks pass, the listener checks to see if it is already connected or dialing
-//! this peer. If it is, it drops the connection. If it isn't, it sends back its own signed handshake message (same as above)
-//! and considers the connection established.
+//! this peer. If it is, it drops the connection. If it isn't, the listener:
+//!
+//! 1. Creates its own signed handshake message (same format as above)
+//! 2. Derives the shared secret from the ephemeral keys
+//! 3. Creates a key confirmation by encrypting the complete handshake transcript using the derived shared secret
```
Comment (dnkolegov-ar) [inline stream/src/public_key/mod.rs]:
```suggestion
//! 3. Creates a key confirmation by encrypting the complete handshake transcript using the confirmation key derived from the shared secret
```

File: stream/src/public_key/mod.rs [hunk 13]
```diff
@@ -11,32 +11,59 @@
...
+//! 4. Sends back a `ListenerResponse` containing both the signed handshake and key confirmation
+//!
+//! This key confirmation serves as cryptographic proof that the listener can correctly derive the shared secret,
+//! ensuring that only parties with the correct key material can proceed.
+//!
+//! ### Message 3: Dialer → Listener (Final Confirmation)
+//! Upon receiving the listener's response, the dialer:
+//!
+//! 1. Verifies the listener's signed handshake message (same checks as the listener performed)
+//! 2. Additionally verifies that the public key returned matches what they expected at the address
```
Comment (dnkolegov-ar) [inline stream/src/public_key/mod.rs]:
```suggestion
//! 2. Additionally verifies that the static public key returned matches what they expected at the address
```

File: stream/src/public_key/mod.rs [hunk 14]
```diff
@@ -11,32 +11,59 @@
...
+//! 3. Derives the shared secret and verifies the listener's key confirmation
```
Comment (dnkolegov-ar) [inline stream/src/public_key/mod.rs]:
```suggestion
//! 3. Computes the X25519 Diffie-Hellman shared secret using its ephemeral private key and the listener’s ephemeral public key. Derives the key confirmation keys and verifies the listener's key confirmation message.
```

File: stream/src/public_key/mod.rs [hunk 15]
```diff
@@ -11,32 +11,59 @@
...
+//! The listener then verifies the dialer's key confirmation. If all checks pass, both parties
+//! consider the connection established with mutual authentication.
 //!
-//! Upon receiving the listener's handshake message, the dialer verifies the same data as the listener and additionally verifies
-//! that the public key returned matches what they expected at the address. If all these checks pass, the dialer considers the
-//! connection established. If not, the dialer drops the connection.
+//! ### Security Properties
+//! This 3-message protocol provides several important security properties:
+//!
+//! - **Mutual Authentication**: Both parties prove knowledge of their private keys through signatures
```
Comment (dnkolegov-ar) [inline stream/src/public_key/mod.rs]:
```suggestion
//! - **Mutual Authentication**: Both parties prove knowledge of their static private keys through signatures
```

File: stream/src/public_key/mod.rs [hunk 16]
```diff
@@ -11,32 +11,59 @@
...
+//! - **Key Confirmation**: Both parties prove they can derive the correct shared secret
+//! - **Transcript Binding**: Key confirmations are bound to the complete handshake exchange
+//! - **Replay Protection**: Timestamps prevent reuse of old handshake messages
```
Comment (dnkolegov-ar) [inline stream/src/public_key/mod.rs]: Do we not need to add that it is correct within the timestamp window?

**Comment by dnkolegov-ar** [comment]
@BrendanChou I added several suggestions, feel free to silently ignore them if you do not find them clarifying the protocol better

File: stream/src/public_key/handshake.rs (hunk 8 above)
Comment (BrendanChou) [reply stream/src/public_key/handshake.rs:230]: I agree.

Yes I made it so that `fn create` and `fn verify` take ownership of the `cipher` so that it can't be re-used afterwards.

While the function signature itself can't guarantee that the `cipher` was not used before passing into the function, there is nowhere else in the code where the cipher is used.

File: stream/src/public_key/connection.rs (hunk 9 above)
Comment (BrendanChou) [reply stream/src/public_key/connection.rs:252]: Yes I believe this mirrors the TCP handshake itself structured as `1. SYN, 2. SYN-ACK, 3. SYN`.
From the perspective of both the listener and the dialer, the handshake should take 1 RTT. That is, if the time to send a message between parties is `t`, then the handshake timeout can be larger than `2t` but doesn't have to be as long as `3t`. Let me know if this makes sense:

`t0`: Dialer starts TCP handshake, sends SYN
`t1`: Listener receives SYN, starts TCP handshake, sends SYN-ACK
`t2`: Dialer receives SYN-ACK, sends ACK, ends TCP handshake, initiates commonware handshake timeout, sends DialerHandshake
`t3`: Listener receives ACK, ends TCP handshake, initiates commonware handshake timeout, receives DialerHandshake, sends ListenerHandshake+KeyConfirmation
`t4`: Dialer receives ListenerHandshake+KeyConfirmation, sends KeyConfirmation, ends commonware handshake
`t5`: Listener receives KeyConfirmation, ends commonware handshake

Handshake timeout for the dialer lasts from `t2-4` and handshake timeout for listener lasts from `t3-5`

**Review by dnkolegov-ar — APPROVED** [review]

File: stream/src/public_key/handshake.rs [hunk 17]
```diff
@@ -198,6 +202,119 @@ impl<C: PublicKey> EncodeSize for Signed<C> {
     }
 }
 
+/// Key confirmation message used during the handshake process.
+///
+/// This struct contains cryptographic proof that a party can correctly derive
+/// the shared secret from the Diffie-Hellman exchange. It prevents attacks where
+/// an adversary might forward handshake messages without actually knowing the
+/// corresponding private keys.
```
Comment (patrick-ogrady) [inline stream/src/public_key/handshake.rs:210]: nit: explicitly list the private keys referred to here.

File: stream/src/public_key/handshake.rs [hunk 18]
```diff
@@ -198,6 +202,119 @@ impl<C: PublicKey> EncodeSize for Signed<C> {
...
+    /// The signed handshake from the listener
+    handshake: Signed<C>,
+
+    /// Key confirmation that the listener can derive the shared secret
+    key_confirmation: KeyConfirmation,
+}
+
+impl<C: PublicKey> ListenerResponse<C> {
+    /// Create a new listener response with the given handshake and key confirmation.
+    pub fn new(handshake: Signed<C>, key_confirmation: KeyConfirmation) -> Self {
```
Comment (patrick-ogrady) [inline stream/src/public_key/handshake.rs]: nit: `confirmation` (type is implies it is `KeyConfirmation`)

File: stream/src/public_key/handshake.rs [hunk 19]
```diff
@@ -198,6 +202,119 @@ impl<C: PublicKey> EncodeSize for Signed<C> {
...
+    /// AEAD tag of the encrypted proof demonstrating knowledge of the shared secret.
+    tag: Tag<ChaCha20Poly1305>,
+}
+
+impl KeyConfirmation {
+    /// Create a new key confirmation using the provided cipher and handshake transcript.
+    ///
+    /// The confirmation encrypts the handshake transcript to demonstrate
+    /// knowledge of the shared secret and bind the confirmation to the entire handshake exchange.
+    pub fn create(mut cipher: ChaCha20Poly1305, transcript: &[u8]) -> Result<Self, Error> {
```
Comment (patrick-ogrady) [inline stream/src/public_key/handshake.rs:227]: Can you add a comment that this `cipher` isn't the one used for ongoing stream encryption (as noted in another comment, the fear is that it may use the same nonce multiple times and IMO would be good to call out why that can't be the case).

File: stream/src/public_key/mod.rs [hunk 20]
```diff
@@ -1,67 +1,98 @@
...
+//! - It supports arbitrary cryptographic schemes
+//! - No protocol negotiation (only one way to connect)
+//! - Simple implementation (few hundred lines of code)
+//! - Can be simulated deterministically
+//!
+//! The **dialer** initiates connection to a known address/identity (public key)
+//! and the **listener** receives this connection. The protocol works as follows:
+//!
+//! ### Message 1: Dialer → Listener (Initial Handshake)
+//! Upon establishing a TCP connection, the dialer sends a signed handshake message to the listener.
```
Comment (patrick-ogrady) [inline stream/src/public_key/mod.rs]: I believe this actually works over an arbitrary `commonware_runtime::{Sink, Stream}`? Seems nice to call that out.

File: stream/src/public_key/mod.rs [hunk 21]
```diff
@@ -1,67 +1,98 @@
...
+//! This message contains the dialer's signature and static public key, plus:
```
Comment (patrick-ogrady) [inline stream/src/public_key/mod.rs]: nit: seems odd to include two message contents here and then a list of three others below?

File: stream/src/public_key/mod.rs [hunk 22]
```diff
@@ -1,67 +1,98 @@
...
+//! This handshake is used instead of TLS, Noise, WireGuard, etc. because:
+//! - It supports arbitrary cryptographic schemes
+//! - No protocol negotiation (only one way to connect)
+//! - Simple implementation (few hundred lines of code)
+//! - Can be simulated deterministically
+//!
+//! The **dialer** initiates connection to a known address/identity (public key)
+//! and the **listener** receives this connection. The protocol works as follows:
+//!
+//! ### Message 1: Dialer → Listener (Initial Handshake)
```
Comment (patrick-ogrady) [inline stream/src/public_key/mod.rs]: nit: for consistency, put a `\n` after this title

File: stream/src/public_key/mod.rs [hunk 23]
```diff
@@ -1,67 +1,98 @@
...
+//! Upon establishing a TCP connection, the dialer sends a signed handshake message to the listener.
+//! This message contains the dialer's signature and static public key, plus:
+//!
+//! - The listener's expected public key
+//! - The dialer's ephemeral public key (for establishing a shared secret)
+//! - The current timestamp (for replay attack prevention)
+//!
+//! ### Message 2: Listener → Dialer (Response with Key Confirmation)
```
Comment (patrick-ogrady) [inline stream/src/public_key/mod.rs]: For consistency, put a ` \n` after.

File: stream/src/public_key/mod.rs [hunk 24]
```diff
@@ -1,67 +1,98 @@
...
+//! The listener verifies:
+//! - Public keys are well-formatted
+//! - Timestamp is valid (not too old, not too far in the future)
+//! - Signature is valid
+//! - It is not already connected to or dialing this peer
```
Comment (patrick-ogrady) [inline stream/src/public_key/mod.rs]: This is not the concern of `stream`. I think we could put this in italics but putting it here could lead to someone using `stream` not preventing this.

File: stream/src/public_key/mod.rs [hunk 25]
```diff
@@ -1,67 +1,98 @@
...
+//!
+//! If all checks pass, the listener:
+//!
+//! 1. Creates its own signed handshake message
+//! 2. Computes the X25519 Diffie-Hellman shared secret
+//! 3. Creates a key confirmation by encrypting the handshake transcript
+//! 4. Sends back a `ListenerResponse` containing both the signed handshake and key confirmation
+//!
+//! ### Message 3: Dialer → Listener (Final Confirmation)
```
Comment (patrick-ogrady) [inline stream/src/public_key/mod.rs]: nit: follow with `\n`

File: stream/src/public_key/mod.rs [hunk 26]
```diff
@@ -1,67 +1,98 @@
...
+//! The dialer:
+//!
+//! 1. Verifies the listener's signed handshake message
+//! 2. Verifies the returned static public key matches expectations
+//! 3. Computes the shared secret and verifies the listener's key confirmation
+//! 4. Creates its own key confirmation
+//! 5. Sends the key confirmation to complete mutual authentication
+//!
+//! ### Security Properties
```
Comment (patrick-ogrady) [inline stream/src/public_key/mod.rs:35]: nit: follow with `\n`

File: stream/src/public_key/mod.rs [hunk 27]
```diff
@@ -1,67 +1,98 @@
...
+//!
+//! - **Mutual Authentication**: Both parties prove knowledge of their static private keys through
+//!   signatures
+//! - **Key Confirmation**: Both parties prove they can derive the correct shared secret
+//! - **Transcript Binding**: Key confirmations are bound to the complete handshake exchange
+//! - **Replay Protection**: Timestamps prevent reuse of old handshake messages within the configured timestamp window
+//! - **Forward Secrecy**: Ephemeral keys ensure compromise of long-term static keys doesn't affect past
+//!   or future sessions
+//!
+//! A configurable deadline is enforced for handshake completion to protect against DOS attacks by
```
Comment (patrick-ogrady) [inline stream/src/public_key/mod.rs]: nit: I've written it as `DoS` in other places

File: stream/src/public_key/mod.rs [hunk 28]
```diff
@@ -1,67 +1,98 @@
...
 //!
 //! ## Encryption
 //!
-//! During the handshake (described above), a shared x25519 secret is established using a
-//! Diffie-Hellman Key Exchange. This x25519 secret is then used in-conjunction with the handshake
-//! data in a key-derivation-function to create a pair of ChaCha20-Poly1305 ciphers. One cipher per
-//! direction allows for encryption of all messages.
+//! During the handshake, a shared X25519 secret is established using
+//! Diffie-Hellman key exchange. This secret is combined with the handshake
+//! transcript to derive separate ChaCha20-Poly1305 ciphers:
```
Comment (patrick-ogrady) [inline stream/src/public_key/mod.rs]: nit: I'd suggest explicitly saying "four ciphers" as well

File: stream/src/public_key/mod.rs [hunk 29]
```diff
@@ -1,67 +1,98 @@
...
-//! overflow, a new connection should be established.
-//!
-//! This simple coordination prevents nonce reuse (which would allow for messages to be decrypted)
-//! and saves a small amount of bandwidth (no need to send the nonce alongside the encrypted
-//! message). This also avoids accidental reuse of a nonce over long-lived connections (for example
-//! when setting it to be a small hash as in XChaCha20-Poly1305).
+//! 1 billion messages per second—sufficient for all practical use cases. This
+//! approach ensures that well-behaving peers can remain connected
+//! indefinitely as long as they both stay online (maximizing p2p network stability). In the unlikely case of
+//! counter overflow, a new connection should be established.
```
Comment (patrick-ogrady) [inline stream/src/public_key/mod.rs]: nit: the connection will be terminated and a new one should be established.

File: stream/src/public_key/nonce.rs [hunk 30]
```diff
@@ -1,15 +1,29 @@
 use crate::Error;
 use chacha20poly1305::Nonce;
 
-/// A struct that holds the nonce information. Holds a counter value that is incremented each time
-/// the nonce is used. Is able to be incremented up-to 96 bits (12 bytes) before overflowing.
+/// A struct that holds the nonce information for ChaCha20-Poly1305 encryption.
+///
+/// This struct manages a 96-bit counter that is used to generate unique nonces
```
Comment (patrick-ogrady) [inline stream/src/public_key/nonce.rs]: nit: in the long-form comments above, you refer to this as a `12-byte` counter

**Review by patrick-ogrady — COMMENTED** [review]
Left some comments on wording but didn't find anything wrong with the code!

Still mulling over the tweaks (as this is a far diff from what we originally had).

**Comment by dnkolegov-ar** [comment]
> than making the dialer send one more message within a pre-existing timeout (the code here).

It is possible to implement another variant: a dialer does not send a confirmation message explicitly. However, in this case, the listener must wait for an encrypted transport message from the dialer, and only after receiving it, is the listener allowed to send transport messages to the dialer.

**Comment by patrick-ogrady** [comment]
> > than making the dialer send one more message within a pre-existing timeout (the code here).
> 
> It is possible to implement another variant: a dialer does not send a confirmation message explicitly. However, in this case, the listener must wait for an encrypted transport message from the dialer, and only after receiving it, is the listener allowed to send transport messages to the dialer.

Ser, there are already infinite variants to write 😉

File: stream/src/public_key/mod.rs (hunk 20 above)
Comment (BrendanChou) [reply stream/src/public_key/mod.rs]: Might be more confusing than it's worth. I removed the discussion of TCP

**Comment by BrendanChou** [comment]
I think half-key confirmation (3rd one below) is probably the worst option out of everything.

- Explicit key confirmation
- No key confirmation until you get a message from the other party
- Key confirmation for the listener->dialer route but no key confirmation until you get a message for the dialer->listener route

Sticking to explicit key confirmation only adds a half RTT for the listener and can still keep the handshake timeout at >1 RTT for both dialer and listener. I think it's basically optimal

**Comment by patrick-ogrady** [comment]
I concur this is a good change because it prevents an "intercepting adversary" from ever successfully opening a connection with a listener.

While said adversary would not be able to decrypt any messages, completing a handshake [1] can throw off the rate limiting (p2p limits how connections we try to form with peers per X), [2] results in the listener consuming useless bandwidth (users of p2p often broadcast messages to all connected peers), and [3] results in the collection of potentially sensitive encrypted data (if used with a DKG for example).

I took a while to come to this conclusion because I assumed any attacker able to intercept a handshake message would also be able to mess with a TCP stream (and undermine the connection anyways). However, it is MUCH easier to collect packets (like a handshake) than it is to meaningfully impede a TCP stream (so there is a practical delta this does defend against).
