### PR TITLE
[codec] Add `read/decode` configuration. Split `Codec` into sub-traits.

### LINKED ISSUE #687: [codec] Add optional configuration for `read`
Necessary for safety (DOS protection via "unlimited" parsing), the `read` and `decode` functions in `Codec` should contain an additional argument for a configuration, similar to the following. The `decode` method would pass-on the configuration to the `read` method.

This would make the trait look like the following:
```
pub trait Codec<C>: Sized {
    fn read(buf: &mut impl Buf, cfg: C) -> Result<Self, Error>;
    fn decode(mut buf: impl Buf, cfg: C) -> Result<Self, Error>;
    ...
}
```

Many types would require zero configuration, so the type `C` would be `()`. For example:

```
impl Codec<()> for u8 {
    fn read(buf: &mut impl Buf, _: ()) -> Result<Self, Error> {
        ...
    }
    ...
}
```

The vector implementation may look something like this:

```
impl<R: RangeBounds<usize>, C: Copy, T: Codec<C>> Codec<(R, C)> for Vec<T> {
    #[inline]
    fn write(&self, buf: &mut impl BufMut) {
        self.len().write(buf);
        for item in self {
            item.write(buf);
        }
    }

    #[inline]
    fn len_encoded(&self) -> usize {
        let len = varint::size(self.len() as u64);
        self.iter().map(Codec::len_encoded).sum::<usize>() + len
    }

    #[inline]
    fn read(buf: &mut impl Buf, (range, cfg): (R, C)) -> Result<Self, Error> {
        let len = <usize>::read(buf, ())?;
        if !range.contains(&len) {
            return Err(Error::InvalidLength(len));
        }
        let mut vec = Vec::with_capacity(len);
        for _ in 0..len {
            vec.push(T::read(buf, cfg)?);
        }
        Ok(vec)
    }
}
```

This allows specifying a range of lengths for which we will accept when reading a vector.

```
// Assumes that `Codec<()>` is implemented for `Signature`

// Any length
<Vec<Signature>>::decode(msg, (.., ()));

// At-most-len
<Vec<Signature>>::decode(msg, (..=len, ()));

// Exactly len
<Vec<Signature>>::decode(msg, (len..=len, ()));
```

------

⚠ Since the `write` and `encode` methods do not require any configuration, it is likely that as part of this change, we should split these methods out into their own trait. Perhaps a `Decode` and `Encode` trait instead of a single `Codec` trait. This prevents us from having to specify the (irrelevant!) `C` trait to use when encoding/writing a type

------

Example below of more nesting of config types

```
pub struct PayloadCodecConfig<R1: RangeBounds<usize>, R2: RangeBounds<usize>> {
    /// The number of peers that can be sent in a `Peers` message.
    pub num_peers: R1,
    /// The number of bits that can be sent in a `BitVec` message.
    pub num_bitvec: R2,
}

pub enum Payload<C: Verifier> {
    BitVec(BitVec),
    Peers(Vec<SignedPeerInfo<C>>),
    Data(Data),
}

impl<R1: RangeBounds<usize>, R2: RangeBounds<usize>, C: Verifier> Codec<PayloadCodecConfig<R1, R2>>
    for Payload<C>
{
    fn write(&self, buf: &mut impl BufMut) {
        match self {
            Payload::BitVec(bitvec) => {
                0u8.write(buf);
                commonware_codec::Codec::<R2>::write(bitvec, buf); // This complication is removed if Codec is split into two traits
            }
            Payload::Peers(peers) => {
                1u8.write(buf);
                commonware_codec::Codec::<R1>::write(peers, buf); // This complication is removed if Codec is split into two traits
            }
            Payload::Data(data) => {
                2u8.write(buf);
                data.write(buf);
            }
        }
    }

    fn read(buf: &mut impl Buf, cfg: PayloadCodecConfig<R1, R2>) -> Result<Self, Error> {
        let payload_type = <u8>::read(buf, ())?;
        match payload_type {
            0 => {
                let bitvec = BitVec::read(buf, cfg.num_bitvec)?;
                Ok(Payload::BitVec(bitvec))
            }
            1 => {
                let peers = Vec::<SignedPeerInfo<C>>::read(buf, (cfg.num_peers, ()))?;
                Ok(Payload::Peers(peers))
            }
            2 => {
                let data = Data::read(buf, ())?;
                Ok(Payload::Data(data))
            }
            _ => Err(Error::Invalid(
                "p2p::authenticated::Payload",
                "Invalid type",
            )),
        }
    }
    ...
}

### PR DESCRIPTION
**Pull request by BrendanChou**
Fixes #687

### CODE REVIEW

File: codec/src/lib.rs [hunk 1]
```diff
@@ -30,26 +30,29 @@
...
 //!
-//!     fn read(buf: &mut impl Buf) -> Result<Self, Error> {
+//! // Implement the Decode trait
+//! impl Decode<()> for Point {
+//!     fn read(buf: &mut impl Buf, _: ()) -> Result<Self, Error> {
 //!         // Basic types can be inferred by the return type
-//!         let xy = <(u64, u64)>::read(buf)?;
-//!         let z = <Option<u32>>::read(buf)?;
-//!         let metadata = <[u8; 11]>::read(buf)?;
+//!         let xy = <(u64, u64)>::read(buf, ((), ()))?;
```
Comment (patrick-ogrady) [inline codec/src/lib.rs]: I wonder if it makes sense to treat normal `read()` as having the empty cfg by default so that we don't need to  use these empty limits all over?

And then we could do `read_cfg()` if you want to provide a custom config? `read()` could be implemented as a default function in the trait?

Comment (patrick-ogrady) [reply codec/src/lib.rs]: Or I suppose we could do `DecodeExt` that offers this functionality (and leave `read()` as unimplemented if a config is required).

File: broadcast/src/buffered/ingress.rs [hunk 2]
```diff
@@ -48,7 +48,7 @@ impl<D: Digest, M: Digestible<D>> Mailbox<D, M> {
     }
 }
 
-impl<D: Digest, M: Codec + Digestible<D>> Broadcaster for Mailbox<D, M> {
+impl<Cfg, D: Digest, M: Codec<Cfg> + Digestible<D>> Broadcaster<Cfg> for Mailbox<D, M> {
```
Comment (patrick-ogrady) [inline broadcast/src/buffered/ingress.rs]: In some places we enforce that `C`/`Cfg` is `Copy + Send + 'static` and in others we don't. I recommend defining a `Cfg` trait in `Codec` that implements `Copy + Send + 'static` with no required functions to force standardization here.

File: codec/src/codec.rs [hunk 3]
```diff
@@ -3,53 +3,122 @@
...
+    /// Returns an error if decoding fails (e.g., invalid data, not enough bytes initially).
+    fn read_cfg(buf: &mut impl Buf, cfg: Cfg) -> Result<Self, Error>;
+}
+
+/// Trait for types that can be encoded to a buffer.
+pub trait Encode: Write {
     /// Returns the encoded length of this value.
+    ///
+    /// This method MUST return the exact number of bytes that will be written by `write()`.
     fn len_encoded(&self) -> usize;
```
Comment (patrick-ogrady) [inline codec/src/codec.rs]: Should we use `unimplemented!()` here so that `EncodeFixed` doesn't need to do this?

File: codec/src/codec.rs [hunk 4]
```diff
@@ -3,53 +3,122 @@
...
     const LEN_ENCODED: usize;
 
-    /// Returns the encoded length of this value.
-    ///
-    /// Should not be overridden by implementations.
-    fn len_encoded(&self) -> usize {
-        Self::LEN_ENCODED
-    }
+    /// Overwrites [`Size::FIXED_SIZE`] with the encoded length.
+    const FIXED_SIZE: Option<usize> = Some(Self::LEN_ENCODED);
```
Comment (patrick-ogrady) [inline codec/src/codec.rs]: nit: Should we strive to either have `LEN_ENCODED` or `FIXED_SIZE`? We may be able to do a nice simplification if we just require `FIXED_SIZE` on all types (but it can be null) -> the `len_encoded()` call can then use this if some or passthrough to `Self` if not (I think)?

In any case, feels weird to have both here.

File: codec/src/types/primitives.rs [hunk 5]
```diff
@@ -67,102 +62,154 @@ impl Codec for bool {
...
+    #[inline]
+    fn len_encoded(&self) -> usize {
+        let len = u32::try_from(self.len()).expect("Vec length exceeds u32");
+        varint::size(len) + self.iter().map(Encode::len_encoded).sum::<usize>()
+    }
+}
+
+impl<R: RangeBounds<usize>, Cfg: Copy, T: Read<Cfg>> Read<(R, Cfg)> for Vec<T> {
+    #[inline]
+    fn read_cfg(buf: &mut impl Buf, (range, cfg): (R, Cfg)) -> Result<Self, Error> {
```
Comment (patrick-ogrady) [inline codec/src/types/primitives.rs]: I would expect the `cfg` to just be RangeBounds? Is there a reason we need to keep both?

Ahhh for the inner type config.

Comment (patrick-ogrady) [reply codec/src/types/primitives.rs]: I wonder if it makes sense to implement something like this for just RangeBounds for inner types that have no Cfg? I expect that to be a very common call.

File: codec/src/codec.rs [hunk 6]
```diff
@@ -3,53 +3,122 @@
...
+    /// For types with a known size, this method first checks that the buffer has the expected size.
     ///
-    /// Returns an error if there is an error while decoding or if there is extra data remaining
-    /// after decoding the value from the buffer.
-    fn decode<B: Buf>(mut buf: B) -> Result<Self, Error> {
-        let result = Self::read(&mut buf);
+    /// (Provided method).
+    fn decode_cfg(mut buf: impl Buf, cfg: Cfg) -> Result<Self, Error> {
+        // If we can, before reading, check that the buffer has the expected size.
+        if let Some(size) = Self::FIXED_SIZE {
```
Comment (patrick-ogrady) [inline codec/src/codec.rs]: If we dropped `FIXED_SIZE` (to only have LEN_ENCODED), we would just lose this early optimizaation?

File: codec/src/codec.rs [hunk 7]
```diff
@@ -3,53 +3,122 @@
...
+/// Trait for types that can be encoded and decoded.
+pub trait Codec<Cfg = ()>: Encode + Decode<Cfg> {}
+
+/// Automatically implement `Codec` for types that implement `Encode` and `Decode`.
+impl<Cfg, T: Encode + Decode<Cfg>> Codec<Cfg> for T {}
+
+/// Trait for types with a known, fixed encoded length.
+pub trait FixedSize: Size {
+    /// The length of the encoded value.
     const LEN_ENCODED: usize;
```
Comment (patrick-ogrady) [inline codec/src/codec.rs]: I like the sound of `FIXED_SIZE` much better than `LEN_ENCODED` (more clearly implies this is the fixed const)...if we align on only one const here, I think we should think about `LEN_ENCODED` a tad more.

File: codec/src/types/primitives.rs (hunk 5 above)
Comment (BrendanChou) [reply codec/src/types/primitives.rs]: The issue is that we can only implement one of the following, otherwise we get a compiler error for conflicting implementations:

```
error[E0119]: conflicting implementations of trait `codec::Read<(_, _)>` for type `Vec<_>`
   --> codec/src/types/primitives.rs:190:1
    |
174 | impl<R: RangeBounds<usize>, T: Read<()>> Read<R> for Vec<T> {
    | ----------------------------------------------------------- first implementation here
...
190 | impl<R: RangeBounds<usize>, Cfg: Copy, T: Read<Cfg>> Read<(R, Cfg)> for Vec<T> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `Vec<_>`
```

File: codec/src/codec.rs (hunk 7 above)
Comment (BrendanChou) [reply codec/src/codec.rs]: `ENCODED_SIZE`?

File: codec/src/codec.rs [hunk 8]
```diff
@@ -3,53 +3,103 @@
...
+
+// Automatically implement `Config` for matching types.
+impl<T: Clone + Send + 'static> Config for T {}
+
+/// Trait for types that can be written (encoded) to a buffer.
+pub trait Write {
+    /// Encodes this value by writing to a buffer.
+    ///
+    /// Implementations should panic if the buffer doesn't have enough capacity.
     fn write(&self, buf: &mut impl BufMut);
```
Comment (patrick-ogrady) [inline codec/src/codec.rs:61]: Wondering if we should bit the bullet now and also integrate `cfg` with `write`? I suspect we'll "eventually" want this but not sure when.

File: codec/src/codec.rs (hunk 7 above)
Comment (patrick-ogrady) [reply codec/src/codec.rs]: I want something that makes it clear this is fixed

Comment (patrick-ogrady) [reply codec/src/codec.rs]: (and can't be confused with implemented `len_encoded` (or whatever we call that)

File: codec/src/codec.rs (hunk 8 above)
Comment (BrendanChou) [reply codec/src/codec.rs:61]: Let's omit it for now, I'm not convinced we should add this as it starts to add more complexity and additional type proliferation. I think it's standard to NOT use a config when encoding.

File: codec/src/codec.rs (hunk 7 above)
Comment (BrendanChou) [reply codec/src/codec.rs]: Changed to `SIZE`

File: codec/src/codec.rs (hunk 3 above)
Comment (BrendanChou) [reply codec/src/codec.rs]: I didn't 100% understand your meaning, but if a type is `FixedSize`, it just has to specify the `const SIZE: usize` constant, and `Encode` is automatically implemented for them (they don't have to implement `len_encoded` to return `SIZE`) due to the blanket implementation.

I changed the names of the variables, but see this comment https://github.com/commonwarexyz/monorepo/pull/699#discussion_r2038424100

File: codec/src/codec.rs [hunk 9]
```diff
@@ -16,6 +16,25 @@ pub trait RangeConfig: Config + RangeBounds<usize> {}
...
+    fn encode_size(&self) -> usize;
+}
+
+// Automatically implement `EncodeSize` for types with a fixed size.
+impl<T: FixedSize> EncodeSize for T {
+    fn encode_size(&self) -> usize {
+        Self::SIZE
+    }
+}
+
```
Comment (BrendanChou) [inline codec/src/codec.rs]: This should hopefully make it a lot clearer what's going on and make it more obvious that clients have to implement one or the other, but not both

File: broadcast/src/buffered/engine.rs [hunk 10]
```diff
@@ -171,7 +177,7 @@ impl<
                     };
 
                     // Decode the message
-                    let message = match M::decode(msg) {
+                    let message = match M::decode_cfg(msg, self.decode_config.clone()) {
```
Comment (patrick-ogrady) [inline broadcast/src/buffered/engine.rs]: I recommend making this `decode_cfg(msg, &cfg)` (so we don't need to clone this object for each decode.

File: codec/src/lib.rs [hunk 11]
```diff
@@ -2,64 +2,180 @@
...
+//!
+//! # Implementing for Custom Types
 //!
-//! User-defined types can be serialized and deserialized by implementing the `Codec` trait.
-//! For types with a constant encoded size, optionally implement the `SizedCodec` trait.
+//! You typically need to implement [`Write`], [`EncodeSize`] (unless [`FixedSize`]), and [`Read<Cfg>`]
+//! for your custom structs and enums.
 //!
-//! # Example
+//! ## Example (Variable Size Type)
```
Comment (patrick-ogrady) [inline codec/src/lib.rs:107]: nit: Recommend doing fixed size before variable size

File: codec/src/types/net.rs [hunk 12]
```diff
@@ -1,101 +1,89 @@
...
-    fn read(buf: &mut impl Buf) -> Result<Self, Error> {
+    fn read_cfg(buf: &mut impl Buf, _: ()) -> Result<Self, Error> {
         let bits = <u32>::read(buf)?;
         Ok(Ipv4Addr::from_bits(bits))
     }
 }
 
-impl SizedCodec for Ipv4Addr {
-    const LEN_ENCODED: usize = u32::LEN_ENCODED;
+impl FixedSize for Ipv4Addr {
```
Comment (patrick-ogrady) [inline codec/src/types/net.rs:22]: I LOVE this change. SOOOOO nice to not have to re-implement `len_encoded()`

File: codec/src/types/vec.rs [hunk 13]
```diff
@@ -0,0 +1,72 @@
+//! Implementations of Codec for common types
+
+use crate::{varint, Config, EncodeSize, Error, RangeConfig, Read, Write};
+use bytes::{Buf, BufMut};
+
+// Vec implementation
+impl<T: Write> Write for Vec<T> {
+    #[inline]
+    fn write(&self, buf: &mut impl BufMut) {
+        let len = u32::try_from(self.len()).expect("Vec length exceeds u32");
```
Comment (patrick-ogrady) [inline codec/src/types/vec.rs:12]: nit: suggest writing a small blurb about why `u32`

File: codec/src/codec.rs [hunk 14]
```diff
@@ -1,63 +1,156 @@
...
+    /// The size of the encoded value (in bytes).
+    const SIZE: usize;
+}
+
+/// Trait for types that can provide their encoded size in bytes.
+///
+/// This must be implemented by all encodable types. For types implementing [`FixedSize`], this
+/// trait is implemented automatically. For variable-size types, this requires calculating the size
+/// based on the value.
+pub trait EncodeSize {
```
Comment (patrick-ogrady) [inline codec/src/codec.rs:44]: nit: I think the `encode_` aspect is implied...wondering if we just call it `fn size()`?

File: codec/src/codec.rs [hunk 15]
```diff
@@ -1,63 +1,156 @@
...
+/// Use `Cfg = ()` if no configuration is needed for a specific type.
+pub trait Read<Cfg: Config = ()>: Sized {
+    /// Reads a value from the buffer using the provided configuration `cfg`.
+    ///
+    /// Implementations should consume the exact number of bytes required from `buf` to reconstruct
+    /// the value.
+    ///
+    /// Returns [`Error`] if decoding fails due to invalid data, insufficient bytes in the buffer,
+    /// or violation of constraints imposed by the `cfg`.
+    fn read_cfg(buf: &mut impl Buf, cfg: Cfg) -> Result<Self, Error>;
```
Comment (patrick-ogrady) [inline codec/src/codec.rs]: As noted elsewhere, I suggest making this `&Cfg`

File: codec/src/codec.rs (hunk 14 above)
Comment (BrendanChou) [reply codec/src/codec.rs:44]: I agree that when looking at this code alone, the `encode_` aspect is obvious and redundant.

However, remember that these types will be used externally. It will be much clearer what `encode_size()` means, which prevent bugs.

For example, consider a collection, say a map, that is encodable. We don't want someone to accidentally call `size()` when they mean to call `len()`. By calling it `encode_size()` we remove this issue and make it more clear where the function is coming from

File: broadcast/src/buffered/engine.rs [hunk 16]
```diff
@@ -88,17 +92,18 @@ pub struct Engine<
 }
 
 impl<
+        Cfg: CodecCfg,
         E: Clock + Spawner + Metrics,
```
Comment (patrick-ogrady) [inline broadcast/src/buffered/engine.rs:95]: nit: I think `E` (context) should remain the first item. I'd prefer to put `Cfg` immediately above `M`

File: p2p/src/authenticated/actors/peer/actor.rs [hunk 17]
```diff
@@ -1,6 +1,11 @@
 use super::{Config, Error, Mailbox, Message, Relay};
-use crate::authenticated::{actors::tracker, channels::Channels, metrics, types};
-use commonware_codec::Codec;
+use crate::authenticated::{
+    actors::tracker,
+    channels::Channels,
+    metrics,
+    types::{self},
```
Comment (patrick-ogrady) [inline p2p/src/authenticated/actors/peer/actor.rs]: Should just be `types`

File: p2p/src/authenticated/config.rs [hunk 18]
```diff
@@ -78,6 +78,12 @@ pub struct Config<C: Scheme> {
     /// key).
     pub tracked_peer_sets: usize,
 
+    /// Maximum number of peers to track in a single peer set.
+    ///
+    /// This is used to limit the size of the bit vec messages, which will take one bit per peer in
+    /// the set. This number can be set to a reasonably high value that we never expect to reach.
+    pub max_peer_set_size: usize,
```
Comment (patrick-ogrady) [inline p2p/src/authenticated/config.rs:85]: Thanks for piping this through (glad we chose this rather than embedding a const deep inside.

File: p2p/src/authenticated/mod.rs [hunk 19]
```diff
@@ -423,7 +423,7 @@ mod tests {
 
     #[test_traced]
     fn test_determinism_one() {
-        for i in 0..10 {
+        for i in 0..1 {
```
Comment (patrick-ogrady) [inline p2p/src/authenticated/mod.rs]: I think this will only run once?

File: p2p/src/authenticated/types.rs [hunk 20]
```diff
@@ -1,8 +1,21 @@
...
-use commonware_codec::{Codec, Error};
+use commonware_codec::{
+    util as CodecUtil, varint, Encode, EncodeSize, Error, RangeConfig, Read, ReadExt, ReadRangeExt,
+    Write,
+};
 use commonware_cryptography::Verifier;
 use std::net::SocketAddr;
 
+#[derive(Clone)]
+pub struct PayloadCodecConfig {
```
Comment (patrick-ogrady) [inline p2p/src/authenticated/types.rs]: Anything against call this just `Config` (and referencing as `types::Config`) or `CodecConfig` (I think the `Payload` part is confusing)

File: p2p/src/authenticated/types.rs [hunk 21]
```diff
@@ -127,22 +195,26 @@ impl<C: Verifier> SignedPeerInfo<C> {
     }
 }
 
-impl<C: Verifier> Codec for SignedPeerInfo<C> {
+impl<C: Verifier> EncodeSize for SignedPeerInfo<C> {
```
Comment (patrick-ogrady) [inline p2p/src/authenticated/types.rs]: nit: I wonder if we should change this to just `PeerInfo` now (as there is no notion without a signature)

**Review by patrick-ogrady — COMMENTED** [review]
Minor nits then g2g!

File: p2p/src/authenticated/mod.rs (hunk 19 above)
Comment (BrendanChou) [reply p2p/src/authenticated/mod.rs]: whoops yeah I was debugging an issue at some point long ago

**Review by patrick-ogrady — APPROVED** [review]
