### PR TITLE
[runtime] Add support for hierarchical tasks

### LINKED ISSUE #1100: Add support for aborting sub-tasks
If we spawn a task (e.g. with `spawn_ref`), and that task spawns sub-tasks, and we drop/abort the parent task, the child sub-tasks aren't aborted. This can lead to unexpected behavior.

For example, a `p2p::authenticated::Network` spawns sub-tasks for the tracker, router, etc.. Aborting the network handle doesn't stop these tasks, meaning that for most intents and purposes the network is still running.

We should have a mechanism in the runtime to enable aborting of sub-tasks when the parent task is aborted.

### PR DESCRIPTION
**Pull request by andresilva**
This PR adds support for hierarchical task management where child tasks are automatically aborted when their parent task completes or is aborted. The implementation introduces a `spawn_child` method to the `Spawner` trait, which creates parent-child relationships between tasks using `futures::future::AbortHandle` for cleanup.

A key principle is that parent-child relationships are tied to the task that spawned them, not to the context itself. When you clone a context (via `Clone::clone` or methods like `with_label`), you get another reference to the same context. This means:
- Tasks spawned with `spawn` from any context (original or cloned) are always independent
- Only tasks spawned with `spawn_child` become children of the current task
- Child tasks are tied to the task that spawned them, not to the context

This design ensures clean separation between different task scopes while maintaining the parent-child abort semantics within each scope. The `spawn_child` method takes `&self` rather than consuming the context, allowing multiple children to be spawned from the same parent context. Unlike `spawn` and `spawn_ref`, `spawn_child` does not set `spawned` to true, as the parent context can legitimately spawn multiple children.

This PR does not migrate any of the existing subsystems to use child tasks. I think this should be done in a follow-up PR (and would require some guidance).

Fixes #1100.

### CODE REVIEW

**Comment by andresilva** [comment]
I am still not entirely sure about the semantics of the API. Also the tests are a bit verbose and involve some duplication.

**Comment by patrick-ogrady** [comment]
This is pretty neat. Haven't had the time to review it yet but thanks for taking a stab.

File: runtime/src/deterministic.rs [hunk 1]
```diff
@@ -738,22 +791,42 @@ impl crate::Spawner for Context {
...
+    fn spawn_child<F, Fut, T>(self, f: F) -> Handle<T>
+    where
+        F: FnOnce(Self) -> Fut + Send + 'static,
+        Fut: Future<Output = T> + Send + 'static,
+        T: Send + 'static,
+    {
+        // Create child context with its own empty children list
+        let child_context = Self {
+            name: self.name.clone(),
+            spawned: self.spawned,
```
[the remark this answers is not in the document]
Comment (BrendanChou) [reply runtime/src/deterministic.rs]: Not clear to me which is correct, but the behavior between `deterministic` and `tokio` seems not to be consistent. Here it inherits the `self.spawned` value and in `tokio`, `spawned` is set to `false`

**Comment by BrendanChou** [comment]
> A key principle is that a `Context` represents a logical scope rather than just a task execution environment - when you clone a context, the clone shares the same scope and children list as the original, meaning all child tasks spawned from any clone of the same context are tracked together and will be aborted as a group.

Forgive me if I don't understand correctly, but then can't there be two contexts that spawn two separate tasks but share `children`? Meaning if one of the two tasks aborts, then ALL children from BOTH tasks are aborted?

**Comment by andresilva** [comment]
IIRC yes, and this is what I meant by not being entirely sure about the semantics (I will check this in detail later as I no longer remember the PR). I think the reason it was done that way was because the `spawn_child` API (like `spawn`) consumes the context, and as such the only way to spawn multiple children is to clone the context. Maybe having both a `spawn_child` and `spawn_child_ref` doesn't make sense, and instead there should only be a single `spawn_child` method that takes `&self` and that allows spawning multiple tasks (unlike `spawn_ref`), and cloning a context would not inherit its children (i.e. it would get an empty vec of children).

**Comment by andresilva** [comment]
@BrendanChou I have updated the PR, I believe it now has cleaner (and less surprising) semantics. I also updated the PR description to reflect the changes.

File: runtime/src/deterministic.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (andresilva) [reply runtime/src/deterministic.rs]: The correct value is for this to be `false` since this is the new context for the child (which hasn't spawned anything yet as it's just being created). Both `deterministic` and `tokio` set this to false explicitly now, although in practice `self.spawned` must have been `false`, so either case is correct.

File: runtime/src/deterministic.rs [hunk 2]
```diff
@@ -577,6 +577,7 @@ pub struct Context {
     executor: Arc<Executor>,
     network: Arc<Network>,
     storage: MeteredStorage<AuditedStorage<MemStorage>>,
+    children: Arc<Mutex<Vec<futures::future::AbortHandle>>>,
```
Comment (BrendanChou) [inline runtime/src/deterministic.rs]: style nit: I suggest importing `futures::future::AbortHandle` so you don't need to say `futures::future::` in-line

File: runtime/src/deterministic.rs [hunk 3]
```diff
@@ -747,15 +752,47 @@ impl crate::Spawner for Context {
...
+
+        // Create child context with its own empty children list
+        let child_context = Self {
+            name: self.name.clone(),
+            spawned: false,
+            executor: self.executor.clone(),
+            network: self.network.clone(),
+            storage: self.storage.clone(),
+            children: Arc::new(Mutex::new(Vec::new())),
+        };
```
Comment (BrendanChou) [inline runtime/src/deterministic.rs]: nit: prefer `let child_context = self.clone();`?

File: runtime/src/deterministic.rs [hunk 4]
```diff
@@ -747,15 +752,47 @@ impl crate::Spawner for Context {
...
     }
 
+    fn spawn_child<F, Fut, T>(&self, f: F) -> Handle<T>
+    where
+        F: FnOnce(Self) -> Fut + Send + 'static,
+        Fut: Future<Output = T> + Send + 'static,
+        T: Send + 'static,
+    {
+        // Ensure a context only spawns one task
+        assert!(!self.spawned, "already spawned");
```
Comment (BrendanChou) [inline runtime/src/deterministic.rs]: Still trying to wrap my head around if this check is necessary

File: runtime/src/tokio/runtime.rs [hunk 5]
```diff
@@ -366,6 +367,7 @@ pub struct Context {
     executor: Arc<Executor>,
     storage: Storage,
     network: Network,
+    children: Arc<Mutex<Vec<futures::future::AbortHandle>>>,
```
Comment (BrendanChou) [inline runtime/src/tokio/runtime.rs]: nit: import `futures::future::AbortHandle`

File: runtime/src/deterministic.rs (hunk 4 above)
Comment (andresilva) [reply runtime/src/deterministic.rs]: It's not needed, I removed it now. It's possible to spawn a child after the context has spawned, those are sibling tasks that are independent.

**Comment by andresilva** [comment]
This was a bit tricky but I think the semantics are now correct (and all cases are covered by tests I think):

```rust
context.spawn(|context| { // task 1
  context.spawn_child({ ... }) // child 1
  context.spawn({ ... }) // task 2
})
```

Child 1 and Task 2 are independent. If Task 1 dies then Child 1 does as well, while Task 2 keeps going. If Task 2 dies then Child 1 and Task 1 are unaffected.

```rust
context.spawn(|context| { // task 1
  context.spawn_ref()({ ... }) // task 2
  context.spawn_child({ ... }) // child 1
})
```

Same as above.

```rust
context.spawn(|context| { // task 1
  context.spawn_child({ ... }) // child 1
  context.clone().spawn_child({ ... }) // child 2
})
```
If Task 1 dies then both Child 1 and 2 die as well. Cloning the context makes no difference since the inheritance is at the task level.

```rust
context.clone().spawn(|context| { // task 1
  context.spawn_child({ ... }) // child 1
})

context.spawn(|context| { ... }) // task 2
```

If Task 2 dies then Child 1 is unaffected.

**Comment by patrick-ogrady** [comment]
> This was a bit tricky but I think the semantics are now correct (and all cases are covered by tests I think):
> 
> ```rust
> context.spawn(|context| { // task 1
>   context.spawn_child({ ... }) // child 1
>   context.spawn({ ... }) // task 2
> })
> ```
> 
> Child 1 and Task 2 are independent. If Task 1 dies then Child 1 does as well, while Task 2 keeps going. If Task 2 dies then Child 1 and Task 1 are unaffected.
> 
> ```rust
> context.spawn(|context| { // task 1
>   context.spawn_ref()({ ... }) // task 2
>   context.spawn_child({ ... }) // child 1
> })
> ```
> 
> Same as above.
> 
> ```rust
> context.spawn(|context| { // task 1
>   context.spawn_child({ ... }) // child 1
>   context.clone().spawn_child({ ... }) // child 2
> })
> ```
> 
> If Task 1 dies then both Child 1 and 2 die as well. Cloning the context makes no difference since the inheritance is at the task level.
> 
> ```rust
> context.clone().spawn(|context| { // task 1
>   context.spawn_child({ ... }) // child 1
> })
> 
> context.spawn(|context| { ... }) // task 2
> ```
> 
> If Task 2 dies then Child 1 is unaffected.

This looks correct to me.

File: runtime/src/deterministic.rs [hunk 6]
```diff
@@ -747,15 +757,38 @@ impl crate::Spawner for Context {
...
     }
 
+    fn spawn_child<F, Fut, T>(&self, f: F) -> Handle<T>
+    where
+        F: FnOnce(Self) -> Fut + Send + 'static,
+        Fut: Future<Output = T> + Send + 'static,
+        T: Send + 'static,
+    {
+        // Create child context
+        let child_context = self.clone();
```
Comment (patrick-ogrady) [inline runtime/src/deterministic.rs]: I actually prefer requiring `spawn_child` consume `self` here (like a normal context spawn).

It should be up to the user to ensure they clone the context for any child (this also allows them to provide a `with_label` here.

File: runtime/src/tokio/runtime.rs [hunk 7]
```diff
@@ -418,15 +427,42 @@ impl crate::Spawner for Context {
...
     }
 
+    fn spawn_child<F, Fut, T>(&self, f: F) -> Handle<T>
+    where
+        F: FnOnce(Self) -> Fut + Send + 'static,
+        Fut: Future<Output = T> + Send + 'static,
+        T: Send + 'static,
+    {
+        // Create child context
+        let child_context = self.clone();
```
Comment (patrick-ogrady) [inline runtime/src/tokio/runtime.rs]: See note in `deterministic` about `self.clone()`.

File: runtime/src/deterministic.rs (hunk 6 above)
Comment (andresilva) [reply runtime/src/deterministic.rs]: I assume that we should only allow a single `spawn_child` or `spawn_ref` as well per context then (this is contrary to what was previously discussed), it's a very niche (and useless) case anyway. Will update the PR.

File: runtime/src/deterministic.rs [hunk 8]
```diff
@@ -747,15 +757,38 @@ impl crate::Spawner for Context {
...
     }
 
+    fn spawn_child<F, Fut, T>(self, f: F) -> Handle<T>
+    where
+        F: FnOnce(Self) -> Fut + Send + 'static,
+        Fut: Future<Output = T> + Send + 'static,
+        T: Send + 'static,
+    {
+        // Store parent's children list
+        let parent_children = self.children.clone();
```
Comment (patrick-ogrady) [inline runtime/src/deterministic.rs:779]: While this may look like a lot of cloning, this is just behind an `Arc` (and its more efficient than some alternatives that avoid this call).
