### PR TITLE
[cryptopgrahy/handshake] increase nonce before checking message len

### LINKED ISSUE #3056: stream e2e fuzz test panicked at stream/fuzz/fuzz_targets/e2e.rs:244
```
cd stream
cargo fuzz run e2e
```

The fuzz test panics after refatoring in https://github.com/commonwarexyz/monorepo/pull/3033

```
thread '<unnamed>' (19789343) panicked at stream/fuzz/fuzz_targets/e2e.rs:244:55:
called `Result::unwrap()` on an `Err` value: HandshakeError(DecryptionFailed)
```

### PR DESCRIPTION
**Pull request by andresilva**
Fix #3056.

### CODE REVIEW

File: cryptography/src/handshake/cipher.rs [hunk 1]
```diff
@@ -200,10 +200,10 @@ impl RecvCipher {
     /// is a simple (and safe) way to handle this scenario.
     #[inline]
     pub fn recv_in_place(&mut self, encrypted_data: &mut [u8]) -> Result<usize, Error> {
+        let nonce = self.nonce.inc()?;
```
Comment (patrick-ogrady) [inline cryptography/src/handshake/cipher.rs:203]: Can you add a regression test for this?

**Comment by cronokirby** [comment]
One question is if we want to support recovery in this case, or if we want to maintain the property that "If DecryptionFailed" is ever returned, then you will never be able to successfully decrypt. (This is the property currently upheld)
