### PR TITLE
[consensus::simplex] Remove dead code, fix minor missing-nullifications bug

### LINKED ISSUE #2095: [consensus::simplex] Remove unreachable code path: honest validator notarizing a proposal that skips a finalized certificate
Looking at the code I think there's a code path that will never be hit under the assumptions of consensus:
https://github.com/commonwarexyz/monorepo/blob/aa95c473241bf2636f5d77799929cc66dcc8dd83/consensus/src/simplex/actors/voter/actor.rs#L1445

A lack of coverage can be seen [here](https://app.codecov.io/gh/commonwarexyz/monorepo/blob/aa95c473241bf2636f5d77799929cc66dcc8dd83/consensus%2Fsrc%2Fsimplex%2Factors%2Fvoter%2Factor.rs#L1445).

If something is `finalized`, that means there cannot be a `nullfication` at the same view, which means that a proposal that "skips" over that view should never have a notarize by at least one honest validator.

After investigating the "unmerged" versions of `simplex` and `threshold_simplex`, the coverage indicated that this code path was not being hit there either.

### PR DESCRIPTION
**Pull request by BrendanChou**
Fixes #2095 

Also:

- Fixes: `at_least_one_honest`
  - Did not properly take into account if a notarization or finalization existed
  - Was a bit confusingly named and confusingly returned the parent digest
  - Changed to `at_least_one_honest_notarization` and returns a `bool` now
- Removed the `missing_nullifications` function since it was just used once, and improperly assumed that the upper range was `self.view` instead of a provided `view`

### CODE REVIEW

File: consensus/src/simplex/actors/voter/actor.rs [hunk 1]
```diff
@@ -1417,52 +1413,32 @@ impl<
                 .await
                 .unwrap();
 
-            // If `>= f+1` notarized a given proposal, then we should backfill missing
-            // notarizations
+            // If at least one honest node notarized a proposal in this view,
+            // then backfill any missing certificates.
             let round = self.views.get(&view).expect("missing round");
-            if let Some(parent) = round.at_least_one_honest() {
-                if parent >= self.last_finalized {
```
Comment (BrendanChou) [inline consensus/src/simplex/actors/voter/actor.rs:1424]: this line always returns true under the assumptions of consensus and honest behavior, so don't check it and just assume you fall into this conditional (and that the `else` below is dead code)

File: consensus/src/simplex/actors/voter/actor.rs [hunk 2]
```diff
@@ -341,13 +341,19 @@ impl<E: Clock, S: Scheme, D: Digest> Round<E, S, D> {
...
-        if self.notarizes.len() <= self.scheme.participants().max_faults() as usize {
-            return None;
+    /// Returns `true` if at least one honest participant has notarized a proposal in this view.
+    pub fn at_least_one_honest_notarization(&self) -> bool {
+        if self.finalization.is_some() {
+            return true;
+        }
+        if self.notarization.is_some() {
+            return true;
         }
```
Comment (andresilva) [inline consensus/src/simplex/actors/voter/actor.rs:365]: Good catch!

File: consensus/src/simplex/actors/voter/actor.rs [hunk 3]
```diff
@@ -1417,52 +1413,32 @@ impl<
...
-                            .fetch(missing_notarizations, missing_nullifications)
-                            .await;
-                    }
-                } else {
-                    // Broadcast last finalized
-                    debug!(
+            if round.at_least_one_honest_notarization() {
+                // Compute certificates that we know are missing
+                let parent = round.proposal.as_ref().unwrap().parent;
+                let missing_notarizations = match self.is_notarized(parent) {
```
Comment (andresilva) [inline consensus/src/simplex/actors/voter/actor.rs:1436]: Don't we still need to check that the parent isn't genesis view?

File: consensus/src/simplex/actors/voter/actor.rs (hunk 1 above)
Comment (andresilva) [reply consensus/src/simplex/actors/voter/actor.rs:1424]: Does it make sense to assert this?

File: consensus/src/simplex/actors/voter/actor.rs [hunk 4]
```diff
@@ -341,13 +341,19 @@ impl<E: Clock, S: Scheme, D: Digest> Round<E, S, D> {
         Some(finalization)
     }
 
-    /// Returns whether at least one honest participant has notarized a proposal.
-    pub fn at_least_one_honest(&self) -> Option<View> {
-        if self.notarizes.len() <= self.scheme.participants().max_faults() as usize {
-            return None;
+    /// Returns `true` if at least one honest participant has notarized a proposal in this view.
+    pub fn at_least_one_honest_notarization(&self) -> bool {
+        if self.finalization.is_some() {
```
Comment (patrick-ogrady) [inline consensus/src/simplex/actors/voter/actor.rs:360]: I didn't think it was worthwhile to handle these cases because fetching anything missing would no longer be necessary?

This was just meant to catch a tip case where we were only seeing `nullifications` (but there was some support for a `proposal` we couldn't vote for and the network couldn't make progress).

Comment (patrick-ogrady) [reply consensus/src/simplex/actors/voter/actor.rs:360]: Your tweak definitely isn't "wrong" that being said (isn't inconsistent with its function).

File: consensus/src/simplex/actors/voter/actor.rs [hunk 5]
```diff
@@ -341,13 +341,19 @@ impl<E: Clock, S: Scheme, D: Digest> Round<E, S, D> {
         Some(finalization)
     }
 
-    /// Returns whether at least one honest participant has notarized a proposal.
-    pub fn at_least_one_honest(&self) -> Option<View> {
-        if self.notarizes.len() <= self.scheme.participants().max_faults() as usize {
-            return None;
+    /// Returns `true` if at least one honest participant has notarized a proposal in this view.
+    pub fn at_least_one_honest_notarization(&self) -> bool {
```
Comment (patrick-ogrady) [inline consensus/src/simplex/actors/voter/actor.rs]: nit: `valid_proposal_ancestry` may be clearer?

File: consensus/src/simplex/actors/voter/actor.rs [hunk 6]
```diff
@@ -587,16 +593,6 @@ impl<
         }
     }
 
-    fn missing_nullifications(&self, parent: View) -> Vec<View> {
-        let mut missing = Vec::new();
-        for view in (parent + 1)..self.view {
```
Comment (patrick-ogrady) [inline consensus/src/simplex/actors/voter/actor.rs:592]: Good catch on `self.view` 👍

File: consensus/src/simplex/actors/voter/actor.rs (hunk 3 above)
Comment (BrendanChou) [reply consensus/src/simplex/actors/voter/actor.rs:1436]: You're absolutely right :^)

In my PR that I'm working on for `certify`, I had modified `is_notarized/is_finalized` to return true for the genesis view. Not-so here.

File: consensus/src/simplex/actors/voter/actor.rs (hunk 5 above)
Comment (BrendanChou) [reply consensus/src/simplex/actors/voter/actor.rs]: I might just have to make the comment clearer. It's basically trying to surmise whether the proposal must be valid via the votes of others. It's not necessarily the case, for example, that it's invalid if you haven't seen enough notarize votes, it just means that you can't be sure.

File: consensus/src/simplex/actors/voter/actor.rs (hunk 4 above)
Comment (BrendanChou) [reply consensus/src/simplex/actors/voter/actor.rs:360]: I see. I definitely think this code could be better overall even after this fix. Just trying to clean it up for now to make other, larger changes easier to reason about

File: consensus/src/simplex/actors/voter/actor.rs (hunk 3 above)
Comment (BrendanChou) [reply consensus/src/simplex/actors/voter/actor.rs:1436]: Added fix https://github.com/commonwarexyz/monorepo/pull/2100/commits/567da3cfad661d3cade73d45da2dfa5e342167fb#diff-4726fd086550e3664cc80d29dc96dea24b8568f1d4a700b324f472f9f9762e26R1424

File: consensus/src/simplex/actors/voter/actor.rs (hunk 1 above)
Comment (BrendanChou) [reply consensus/src/simplex/actors/voter/actor.rs:1424]: I don't think it's necessary, a lot of other worse things would already break down if the byzantine/faulty assumptions were violated.

File: consensus/src/simplex/actors/voter/actor.rs (hunk 4 above)
Comment (BrendanChou) [reply consensus/src/simplex/actors/voter/actor.rs:360]: If there is a finalization or it's an old view, we skip it due to the logic I added here
https://github.com/commonwarexyz/monorepo/pull/2100/commits/567da3cfad661d3cade73d45da2dfa5e342167fb#diff-4726fd086550e3664cc80d29dc96dea24b8568f1d4a700b324f472f9f9762e26L1419

File: consensus/src/simplex/actors/voter/actor.rs (hunk 5 above)
Comment (BrendanChou) [reply consensus/src/simplex/actors/voter/actor.rs]: Attempted to fix via naming/comment here
https://github.com/commonwarexyz/monorepo/pull/2100/commits/fd517284089b911820b11b385aedfc4a3c1f4d97

File: consensus/src/simplex/actors/voter/actor.rs [hunk 7]
```diff
@@ -341,13 +341,26 @@ impl<E: Clock, S: Scheme, D: Digest> Round<E, S, D> {
...
-            return None;
+    /// Returns true if there is evidence that at least one honest participant
+    /// notarized the proposal for this view. This is true if:
+    /// - a finalization for this view exists (implies an honest notarization existed), or
+    /// - a notarization certificate for this view exists, or
+    /// - the number of notarize votes exceeds the maximum number of faulty participants (f),
+    ///   which implies at least one vote came from an honest participant.
+    ///
+    /// Used to decide whether we can safely backfill missing certificates implied by a proposal.
+    pub fn has_honest_notarization(&self) -> bool {
```
Comment (patrick-ogrady) [inline consensus/src/simplex/actors/voter/actor.rs]: nit: `proposal_has_valid_ancestry`

I think `has_honest_notarization` isn't quite specific enough. It sounds like [1] it returns whether or not a round has a notarization, [2] implies that there can be dishonest notarizations, and [3] doesn't indicate there can be both notarizations/nullifications to consider as part of the ancestry.

File: consensus/src/simplex/actors/voter/actor.rs [hunk 8]
```diff
@@ -1417,52 +1419,33 @@ impl<
...
-                            ">= 1 honest notarize for nullified parent"
-                        );
-                        resolver
-                            .fetch(missing_notarizations, missing_nullifications)
-                            .await;
-                    }
-                } else {
-                    // Broadcast last finalized
-                    debug!(
+            if view > self.last_finalized && round.proposal_must_have_valid_ancestry() {
```
Comment (patrick-ogrady) [inline consensus/src/simplex/actors/voter/actor.rs]: should this be comparing `parent` and `self.last_finalized`?

File: consensus/src/simplex/actors/voter/actor.rs [hunk 9]
```diff
@@ -1417,52 +1419,33 @@ impl<
...
-                            ?missing_notarizations,
-                            ?missing_nullifications,
-                            ">= 1 honest notarize for nullified parent"
-                        );
-                        resolver
-                            .fetch(missing_notarizations, missing_nullifications)
-                            .await;
-                    }
-                } else {
-                    // Broadcast last finalized
```
Comment (patrick-ogrady) [inline consensus/src/simplex/actors/voter/actor.rs:1446]: Can you elaborate again why this can't be hit under honest function?

Comment (BrendanChou) [reply consensus/src/simplex/actors/voter/actor.rs:1446]: The issue #2095 explains it well:
> If something is finalized, that means there cannot be a nullfication at the same view, which means that a proposal that "skips" over that view should never have a notarize by at least one honest validator.

Honest validators won't notarize a proposal that "skips" views (the proposal view and the parent view are off by more than 1) unless they have a nullification for every skipped view

File: consensus/src/simplex/actors/voter/actor.rs [hunk 10]
```diff
@@ -1417,52 +1419,33 @@ impl<
...
-                    debug!(
+            if view > self.last_finalized && round.proposal_must_have_valid_ancestry() {
+                // Compute certificates that we know are missing
+                let parent = round.proposal.as_ref().unwrap().parent;
```
Comment (patrick-ogrady) [inline consensus/src/simplex/actors/voter/actor.rs:1435]: `proposal_must_have_valid_ancestry` doesn't imply we have a proposal (could this panic)?

Comment (patrick-ogrady) [reply consensus/src/simplex/actors/voter/actor.rs:1435]: Ah, I guess it must because we won't get any notarizes here until we see leader proposal.

Comment (patrick-ogrady) [reply consensus/src/simplex/actors/voter/actor.rs:1435]: seems worth documenting

File: consensus/src/simplex/actors/voter/actor.rs (hunk 8 above)
Comment (BrendanChou) [reply consensus/src/simplex/actors/voter/actor.rs]: No since imagine the following:
- last_finalized = 1
- view = 3
- parent_view = 1

The node should still go grab the nullification for view 2 if it doesn't already have it

File: consensus/src/simplex/actors/voter/actor.rs (hunk 9 above)
Comment (patrick-ogrady) [reply consensus/src/simplex/actors/voter/actor.rs:1446]: Get it now.

File: consensus/src/simplex/actors/voter/actor.rs (hunk 10 above)
Comment (BrendanChou) [reply consensus/src/simplex/actors/voter/actor.rs:1435]: It's not clear but there are two aspects of `proposal_must_have_valid_ancestry` implying that a proposal exists:
- The name
- The code

I think the name does imply that we have a proposal.

Regarding the code, it is less clear but it does also imply that `proposal` is set. Any notarizes, notarizations, finalizes, and finalizations will populate the field. I can check/assert inside of `proposal_must_have_valid_ancestry` that this is the case

File: consensus/src/simplex/actors/voter/actor.rs [hunk 11]
```diff
@@ -1417,52 +1419,33 @@ impl<
                 .await
                 .unwrap();
 
-            // If `>= f+1` notarized a given proposal, then we should backfill missing
-            // notarizations
+            // If at least one honest node notarized a proposal in this view,
+            // then backfill any missing certificates.
```
Comment (patrick-ogrady) [inline consensus/src/simplex/actors/voter/actor.rs:1431]: I wonder how this logic will evolve when https://github.com/commonwarexyz/monorepo/pull/2107 is merged 🤔

File: consensus/src/simplex/actors/voter/actor.rs (hunk 8 above)
Comment (patrick-ogrady) [reply consensus/src/simplex/actors/voter/actor.rs]: I "think" `view > self.last_finalized` implies `parent >= self.last_finalized` (same issue with gaps right)?

Comment (BrendanChou) [reply consensus/src/simplex/actors/voter/actor.rs]: Yes, `view > self.last_finalized` implies `parent >= self.last_finalized`

File: consensus/src/simplex/actors/voter/actor.rs (hunk 10 above)
Comment (patrick-ogrady) [reply consensus/src/simplex/actors/voter/actor.rs:1435]: Apologize for being so pedantic....every line here carries immense weight

File: consensus/src/simplex/actors/voter/actor.rs [hunk 12]
```diff
@@ -341,13 +341,30 @@ impl<E: Clock, S: Scheme, D: Digest> Round<E, S, D> {
         Some(finalization)
     }
 
-    /// Returns whether at least one honest participant has notarized a proposal.
-    pub fn at_least_one_honest(&self) -> Option<View> {
-        if self.notarizes.len() <= self.scheme.participants().max_faults() as usize {
-            return None;
+    /// Returns true if we are certain that the proposal for this view has a valid ancestry. This is
```
Comment (patrick-ogrady) [inline consensus/src/simplex/actors/voter/actor.rs]: nit: also implies a proposal exists

File: consensus/src/simplex/actors/voter/actor.rs [hunk 13]
```diff
@@ -341,13 +341,30 @@ impl<E: Clock, S: Scheme, D: Digest> Round<E, S, D> {
...
+    /// used to decide whether we can safely backfill missing certificates implied by a proposal. We
+    /// determine this by checking if at least one honest participant notarized the proposal for
+    /// this view. That is, if any of the following are true:
+    /// - a finalization for this view exists, or
+    /// - a notarization certificate for this view exists, or
+    /// - the number of notarize votes exceeds the maximum number of faulty participants.
+    pub fn proposal_must_have_valid_ancestry(&self) -> bool {
```
Comment (patrick-ogrady) [inline consensus/src/simplex/actors/voter/actor.rs]: proposal_has_valid_ancestry

File: consensus/src/simplex/actors/voter/actor.rs [hunk 14]
```diff
@@ -341,13 +341,31 @@ impl<E: Clock, S: Scheme, D: Digest> Round<E, S, D> {
...
-            return None;
+    /// Returns true if the proposal in this view has a valid ancestry (to determine if we should backfill
+    /// missing certificates implied by a proposal).
+    ///
+    /// We determine this by checking if at least one honest participant notarized the proposal for
+    /// this view. That is, if any of the following are true:
+    /// - a finalization for this view exists, or
+    /// - a notarization certificate for this view exists, or
+    /// - the number of notarize votes exceeds the maximum number of faulty participants.
+    pub fn proposal_has_valid_ancestry(&self) -> bool {
```
Comment (patrick-ogrady) [inline consensus/src/simplex/actors/voter/actor.rs]: This function name now implies something about `proposal`'s verification status, which i don't like.

**Review by patrick-ogrady — APPROVED** [review]
