### PR TITLE
[consensus::marshal] Fix: Responses from `broadcast::buffered` are not immediately processed

### LINKED ISSUE #1380: [consensus::marshal] `subscribe` can "hang" from the perspective of the application
`marshal` will occasionally timeout on providing the application a block:
```
verify aborted view=4955 waited=1.897019s
```

This was not an issue in `alto` prior to `marshal.

### PR DESCRIPTION
**Pull request by BrendanChou**
Fixes #1380

### CODE REVIEW

File: consensus/src/marshal/actor.rs [hunk 1]
```diff
@@ -39,27 +40,20 @@ use std::{
...
-    }
-
-    /// Add a responder to the waiter.
-    fn add_responder(&mut self, responder: oneshot::Sender<B>) {
-        self.responders.push(responder);
-    }
+/// A waiter entry that can be canceled.
+struct WaiterEntry<B: Block> {
+    // The responders to the request
+    responders: Vec<oneshot::Sender<B>>,
```
Comment (patrick-ogrady) [inline consensus/src/marshal/actor.rs]: I prefer the term `listeners` here (I think broadcast::buffered also uses responders and suspect that's where this came from)?

**Comment by patrick-ogrady** [comment]
> I think I should create a futures::CancelablePool for code-reuse purposes

Makes sense to me (after doing a quick scan here)

File: utils/src/futures.rs [hunk 2]
```diff
@@ -70,6 +70,82 @@ impl<T: Send> Pool<T> {
     }
 }
 
+/// A hook that can be used to abort a specific future in an [AbortablePool].
+///
+/// When the hook is dropped, the associated future is aborted.
+pub struct AbortHook {
```
Comment (patrick-ogrady) [inline utils/src/futures.rs]: nit: How do you feel about `Aborter` (given it `abort`s)?

File: utils/src/futures.rs [hunk 3]
```diff
@@ -70,6 +70,82 @@ impl<T: Send> Pool<T> {
...
+        let abortable_future = Abortable::new(future, registration);
+        self.pool.push(Box::pin(abortable_future));
+        AbortHook { handle }
+    }
+
+    /// Returns a future that resolves to the next future in the pool that resolves.
+    ///
+    /// If the pool is empty, the future will never resolve.
+    /// Returns `Ok(T)` for successful completion or `Err(Aborted)` for aborted futures.
+    pub fn next_completed(
```
Comment (patrick-ogrady) [inline utils/src/futures.rs:137]: nit: `next()`

File: consensus/src/marshal/actor.rs [hunk 4]
```diff
@@ -39,27 +40,12 @@ use std::{
...
-
-    /// Add a responder to the waiter.
-    fn add_responder(&mut self, responder: oneshot::Sender<B>) {
-        self.responders.push(responder);
-    }
+/// An entry for multiple listeners for a block.
+struct ListenerEntry<B: Block> {
+    // The listeners that are waiting for the block
+    listeners: Vec<oneshot::Sender<B>>,
+    // Hook that aborts the waiter future when dropped
```
Comment (patrick-ogrady) [inline consensus/src/marshal/actor.rs]: ❤️ nice

File: consensus/src/marshal/actor.rs [hunk 5]
```diff
@@ -39,27 +40,12 @@ use std::{
...
-            responders: vec![responder],
-        }
-    }
-
-    /// Add a responder to the waiter.
-    fn add_responder(&mut self, responder: oneshot::Sender<B>) {
-        self.responders.push(responder);
-    }
+/// An entry for multiple listeners for a block.
+struct ListenerEntry<B: Block> {
```
Comment (patrick-ogrady) [inline consensus/src/marshal/actor.rs]: nit: `Listener`?

File: consensus/src/marshal/actor.rs [hunk 6]
```diff
@@ -436,16 +417,22 @@ impl<
...
+                            match self.listeners.entry(commitment) {
                                 Entry::Occupied(mut entry) => {
-                                    entry.get_mut().add_responder(response);
+                                    entry.get_mut().listeners.push(response);
                                 }
                                 Entry::Vacant(entry) => {
                                     let (tx, rx) = oneshot::channel();
                                     buffer.subscribe_prepared(None, commitment, None, tx).await;
-                                    entry.insert(Waiter::new(rx, response));
+                                    let hook = waiters.push(async move {
```
Comment (patrick-ogrady) [inline consensus/src/marshal/actor.rs]: I wonder if it makes sense to make a "wrapper" struct that handles the waiters and listeners?

The logic you introduced here looks solid but seems it could be simplified if we introduced one additional util (unless the generics get too bad)?

**Review by patrick-ogrady — COMMENTED** [review]
Logic/architecture looks solid. Left some small questions/nits.

File: consensus/src/marshal/mod.rs [hunk 7]
```diff
@@ -133,7 +286,7 @@ mod tests {
         }
     }
 
-    #[test_traced("WARN")]
+    #[test]
```
Comment (patrick-ogrady) [inline consensus/src/marshal/mod.rs]: recommend using `test_traced` to get logging?

File: consensus/src/marshal/mod.rs [hunk 8]
```diff
@@ -289,117 +406,291 @@ mod tests {
...
+            }
+
+            let received2 = sub2_rx.await.unwrap();
+            assert_eq!(received2.digest(), block2.digest());
+            assert_eq!(received2.height(), 2);
+        })
+    }
+
+    #[test]
+    fn test_subscribe_blocks_from_different_sources() {
```
Comment (patrick-ogrady) [inline consensus/src/marshal/mod.rs:595]: ❤️

File: utils/src/futures.rs (hunk 3 above)
Comment (BrendanChou) [reply utils/src/futures.rs:137]: `next_completed` for consistency with `futures::Pool` above. I did originally consider `next()` for this, but decided not to for some reason (maybe too close to stream next?)

File: consensus/src/marshal/actor.rs (hunk 6 above)
Comment (BrendanChou) [reply consensus/src/marshal/actor.rs]: I agree there could be (?) room for a util here but not yet confident that I have an idea for one that's general enough yet to be useful in multiple places. In the future I think

File: consensus/src/marshal/actor.rs (hunk 5 above)
Comment (BrendanChou) [reply consensus/src/marshal/actor.rs]: changed to `BlockSubscription`

File: utils/src/futures.rs (hunk 3 above)
Comment (patrick-ogrady) [reply utils/src/futures.rs:137]: I think `next()` in Rust for this is pretty generic (at least I interpret as the correct method name for something like this...we can change in the future but 🤷 ).

File: consensus/src/marshal/mod.rs [hunk 9]
```diff
@@ -117,6 +117,160 @@ mod tests {
...
+        schemes.sort_by_key(|s| s.public_key());
+        let peers: Vec<PublicKey> = schemes.iter().map(|s| s.public_key()).collect();
+
+        let (identity, shares) = generate_shares::<_, V>(context, None, NUM_VALIDATORS, QUORUM);
+        let identity = *poly::public::<V>(&identity);
+
+        (schemes, peers, identity, shares)
+    }
+
+    async fn setup_network_links(oracle: &mut Oracle<P>, peers: &[P], link: Link) {
```
Comment (patrick-ogrady) [inline consensus/src/marshal/mod.rs:260]: JFYI I asked Denis to make some of these helpers exported functions in `p2p::simulated` to avoid further duplication of these utils: https://github.com/commonwarexyz/monorepo/pull/1344#discussion_r2267010502

**Review by patrick-ogrady — APPROVED** [review]
