### PR TITLE
[Array] Remove unnecessary traits

### LINKED ISSUE #622: [utils/codec] Clean up `Array` type
- `Array` should not need `TryFrom<&Vec<u8>>`. `Vec<u8>` can be dereferenced to `&[u8]`
- `Array` should not need `TryFrom<Vec<u8>>`. `Vec<u8>` can be owned by `bytes::Bytes` with zero-copy
- Types implementing Array should ideally have unified logic between `Codec::decode` and `try_from<&[u8]>` (see below)
- `Array` should remove the `read_from` function which should be replaced by its `Codec::decode` implementation (see below)

If a type implements `try_from<&[u8]>`, we could define a new type (here in the example, `SliceCodec`) which attempts uses `try_from` to do zero-copy when possible. This is similar logic to the `read_from` function in `Array` already

```rust
pub trait SliceCodec: SizedCodec + for<'a> TryFrom<&'a [u8]> {
    fn read(reader: &mut impl Reader) -> Result<Self, Error> {
        // Check if enough bytes are available
        if reader.remaining() < Self::LEN_ENCODED {
            return Err(Error::EndOfBuffer);
        }

        // Try zero-copy if the chunk is contiguous and large enough
        let chunk = reader.chunk();
        if chunk.len() >= SELF::LEN_ENCODED {
            let result = Self::try_from(chunk).map_err(|err| Error:Wrapped("Decode", err.into()))?;
            reader.advance(Self::LEN_ENCODED);
            return Ok(result);
        }

        // Fallback to copying
        let mut buf = vec![0; Self::LEN_ENCODED];
        reader.copy_to_slice(&mut buf);
        Self::try_from(&buf).map_err(|err| Error:Wrapped("Decode", err.into()))
    }
}
```

### PR DESCRIPTION
**Pull request by BrendanChou**
Fixes #622

### CODE REVIEW

File: storage/src/adb/operation.rs [hunk 1]
```diff
@@ -154,73 +156,51 @@ impl<K: Array, V: Array> Write for Operation<K, V> {
...
-        if value.len() != Self::SIZE {
-            return Err(Error::InvalidLength);
-        }
-
-        let _ = K::try_from(&value[1..K::SIZE + 1]).map_err(|e| Error::InvalidKey(e))?;
-
-        match value[0] {
+        // Create a vector of the required size and copy the data into it.
+        at_least(buf, Self::SIZE)?;
+        let mut data = vec![0; Self::SIZE];
```
Comment (BrendanChou) [inline storage/src/adb/operation.rs:161]: Current implementation also uses `Vec`, but I was getting compilation errors trying to change it to use `[u8; Self::SIZE]` for some reason it didn't like the usage of the constant due to the generics K/V

Comment (BrendanChou) [reply storage/src/adb/operation.rs:161]: @roberto-bayardo did you run into the same issue which is why this is `Vec<u8>` and not `[u8; 1 + K::SIZE + V::SIZE]`?

File: utils/src/array/mod.rs [hunk 2]
```diff
@@ -45,32 +44,8 @@ pub trait Array:
     + Display
     + AsRef<[u8]>
     + Deref<Target = [u8]>
-    + for<'a> TryFrom<&'a [u8], Error = <Self as Array>::Error>
-    + for<'a> TryFrom<&'a Vec<u8>, Error = <Self as Array>::Error>
-    + TryFrom<Vec<u8>, Error = <Self as Array>::Error>
     + FixedSize
```
Comment (patrick-ogrady) [inline utils/src/array/mod.rs]: nit: Should we instead do `EncodeFixed` here (seems to imply both `Encode + FixedSize`)?

File: cryptography/src/ed25519/scheme.rs [hunk 3]
```diff
@@ -438,21 +364,36 @@ mod tests {
...
             &computed_signature
         ));
     }
 
     fn parse_private_key(private_key: &str) -> PrivateKey {
-        PrivateKey::try_from(commonware_utils::from_hex_formatted(private_key).unwrap()).unwrap()
+        PrivateKey::decode(
+            commonware_utils::from_hex_formatted(private_key)
+                .unwrap()
+                .as_ref(),
```
Comment (patrick-ogrady) [inline cryptography/src/ed25519/scheme.rs:376]: I suppose its probably overkill to have a version of `decode` that consumes `Vec<u8>` (and for unclear benefit)?

File: storage/src/adb/operation.rs [hunk 4]
```diff
@@ -154,73 +156,51 @@ impl<K: Array, V: Array> Write for Operation<K, V> {
...
-    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
-        if value.len() != Self::SIZE {
-            return Err(Error::InvalidLength);
-        }
-
-        let _ = K::try_from(&value[1..K::SIZE + 1]).map_err(|e| Error::InvalidKey(e))?;
-
-        match value[0] {
+        // Create a vector of the required size and copy the data into it.
+        at_least(buf, Self::SIZE)?;
```
Comment (patrick-ogrady) [inline storage/src/adb/operation.rs:160]: This section of code feels like a good opportunity for a helper (for a vec with externally defined size)?

File: storage/src/adb/operation.rs (hunk 1 above)
Comment (roberto-bayardo) [reply storage/src/adb/operation.rs:161]: yup

File: cryptography/src/ed25519/scheme.rs (hunk 3 above)
Comment (BrendanChou) [reply cryptography/src/ed25519/scheme.rs:376]: Yes, since it can consume either `my_vec.as_ref()` as-well-as `Bytes::from(my_vec)`, both of which are no-copy, it would be overkill to add `decode_vec()` IMO

File: utils/src/array/mod.rs (hunk 2 above)
Comment (BrendanChou) [reply utils/src/array/mod.rs]: Originally I had it that way, I figured this might be more clear. Maybe I can just add it explicitly to be `Decode + Encode + FixedSize + EncodeFixed`, which is sort of redundant since `EncodeFixed` is blanket implemented, but should be good

File: storage/src/adb/operation.rs (hunk 1 above)
Comment (roberto-bayardo) [reply storage/src/adb/operation.rs:161]: My assumption is the compiler will be smart enough to optimize the vec allocation away but who knows!

File: utils/src/array/mod.rs (hunk 2 above)
Comment (patrick-ogrady) [reply utils/src/array/mod.rs]: I actually find `EncodeFixed` more clear than `Encode + FixedSize` but maybe that's just me 🦐

File: storage/src/adb/operation.rs (hunk 4 above)
Comment (BrendanChou) [reply storage/src/adb/operation.rs:160]: Yes we have the same issue with [Poly](https://github.com/commonwarexyz/monorepo/blob/f6c7eff445c26a6d569550f7f614336791e5a93c/cryptography/src/bls12381/primitives/poly.rs#L274)

Kind of strange to finagle since we have an implementation for `Vec<u8>` and for `[u8; N]` already, but not for `Vec<T>` of an exact size

Comment (BrendanChou) [reply storage/src/adb/operation.rs:160]: https://github.com/commonwarexyz/monorepo/issues/788

File: storage/src/adb/operation.rs (hunk 1 above)
Comment (BrendanChou) [reply storage/src/adb/operation.rs:161]: https://github.com/commonwarexyz/monorepo/issues/788

**Review by patrick-ogrady — APPROVED** [review]
