### PR TITLE
[p2p] Support hex formatting in `PeerRejected`

### LINKED ISSUE #1978: [stream] Fix `PeerRejected` Formatting
We should support hex-formatting on PeerBlocked: https://github.com/commonwarexyz/monorepo/blob/f3297311265de0f34a4c06cdae9e6f57f0cf20c8/stream/src/lib.rs#L89-L90

We see this in practice:
```
2025-10-23T09:43:34.844522Z DEBUG commonware_p2p::authenticated::discovery::actors::listener: failed to complete handshake err=PeerRejected([77, 117, 20, 15, 102, ..., 130, 19, 13, 12, 114, 99])
```

### PR DESCRIPTION
**Pull request by clabby**
## Overview

Adds hex formatting to the `PeerRejected` error in `stream`.

closes #1978

### CODE REVIEW

File: stream/src/lib.rs [hunk 1]
```diff
@@ -86,7 +86,7 @@ pub enum Error {
     HandshakeError(HandshakeError),
     #[error("unable to decode: {0}")]
     UnableToDecode(CodecError),
-    #[error("peer rejected: {0:X?}")]
+    #[error("peer rejected: {}", hex(_0))]
```
Comment (patrick-ogrady) [inline stream/src/lib.rs:89]: ooo, didn't know you could put functions here.

**Review by patrick-ogrady — APPROVED** [review]
