### PR TITLE
[Codec] Add `HashMap` implementation

### LINKED ISSUE #708: [codec] Add a deterministic `HashMap` implementation
Example code:

```
use crate::{varint, Config, Encode, Error, Read, Write};
use bytes::{Buf, BufMut};
use std::{collections::HashMap, hash::Hash, ops::RangeBounds};

impl<K: Ord + Hash + Eq + Write, V: Write> Write for HashMap<K, V> {
    fn write(&self, buf: &mut impl BufMut) {
        let len = u32::try_from(self.len()).unwrap();
        varint::write(len, buf);

        // Sort the keys to ensure deterministic encoding
        let mut keys: Vec<_> = self.keys().collect();
        keys.sort();
        for key in keys {
            key.write(buf);
            self.get(key).unwrap().write(buf);
        }
    }
}

impl<K: Ord + Hash + Eq + Write + Encode, V: Write + Encode> Encode for HashMap<K, V> {
    fn len_encoded(&self) -> usize {
        let len = u32::try_from(self.len()).unwrap();
        let mut len = varint::size(len);
        for (key, value) in self {
            len += key.len_encoded();
            len += value.len_encoded();
        }
        len
    }
}

impl<
        R: RangeBounds<usize> + Config,
        KCfg: Config,
        VCfg: Config,
        K: Read<KCfg> + Clone + Ord + Hash + Eq,
        V: Read<VCfg> + Clone,
    > Read<(R, KCfg, VCfg)> for HashMap<K, V>
{
    fn read_cfg(
        buf: &mut impl Buf,
        (range, k_cfg, v_cfg): (R, KCfg, VCfg),
    ) -> Result<Self, Error> {
        // Initialize the map with a capacity
        let len = usize::try_from(varint::read::<u32>(buf)?).unwrap();
        if !range.contains(&len) {
            return Err(Error::InvalidLength(len));
        }
        let mut map = HashMap::with_capacity(len);

        // Read the keys and values
        // Keys must be in ascending order for deterministic encoding
        let mut last_key: Option<K> = None;
        for _ in 0..len {
            let key = K::read_cfg(buf, k_cfg.clone())?;
            if let Some(ref last) = last_key {
                if key <= *last {
                    return Err(Error::Invalid("HashMap", "Keys must be in ascending order"));
                }
            }
            last_key = Some(key.clone());

            let value = V::read_cfg(buf, v_cfg.clone())?;
            map.insert(key, value);
        }
        Ok(map)
    }
}
```

### PR DESCRIPTION
**Pull request by BrendanChou**
Fixes #708 

Keys must be sorted (ascending). This provides deterministic guarantees around the encoding.

### CODE REVIEW

File: codec/src/types/map.rs [hunk 1]
```diff
@@ -0,0 +1,270 @@
...
+use std::{collections::HashMap, hash::Hash};
+
+// Write implementation for HashMap
+impl<K: Ord + Hash + Eq + Write, V: Write> Write for HashMap<K, V> {
+    fn write(&self, buf: &mut impl BufMut) {
+        let len = u32::try_from(self.len()).expect("HashMap length exceeds u32::MAX");
+        varint::write(len, buf);
+
+        // Sort the keys to ensure deterministic encoding
+        let mut keys: Vec<_> = self.keys().collect();
```
Comment (patrick-ogrady) [inline codec/src/types/map.rs:21]: It may be faster to convert the whole map to a vec of `(key, value)` and `sort_by(key)`?

File: codec/src/types/map.rs [hunk 2]
```diff
@@ -0,0 +1,270 @@
...
+        let mut map = HashMap::with_capacity(len);
+
+        // Keep track of the last key read
+        let mut last_key: Option<K> = None;
+
+        // Read each key-value pair
+        for _ in 0..len {
+            let key = K::read_cfg(buf, k_cfg)?;
+
+            // Check if keys are in ascending order relative to the previous key
```
Comment (patrick-ogrady) [inline codec/src/types/map.rs:75]: ❤️

File: codec/src/types/map.rs (hunk 1 above)
Comment (patrick-ogrady) [reply codec/src/types/map.rs:21]: ...actually, not sure. That may result in moving a lot more memory around.

Comment (patrick-ogrady) [reply codec/src/types/map.rs:21]: disregard.

File: codec/src/types/map.rs [hunk 3]
```diff
@@ -0,0 +1,270 @@
...
+            if let Some(ref last) = last_key {
+                if key <= *last {
```
Comment (patrick-ogrady) [inline codec/src/types/map.rs]: Do we want to return a different error for duplicate keys vs non-ascending keys?

Comment (patrick-ogrady) [reply codec/src/types/map.rs]: If not, I suggest modifying the error to make it clearer that it isn't quite ascending

**Review by patrick-ogrady — APPROVED** [review]
