### PR TITLE
[Storage] [Runtime] Add configurable faultiness to deterministic storage

### LINKED ISSUE #2911: [Storage] [Runtime] Add deterministic, faulty storage implementation
Unit tests are driven by the deterministic runtime, whose storage implementation is kept in memory and never fails on write. A real storage implementation _can_ fail on write. We should add the ability to run the deterministic storage such that it is possible to deterministically cause it to fail on writes. The failed write may either fail completely (it does nothing) or fail after a partial write. This will allow us to better test crash scenarios in which storage writes fail. In particular, we should be able to use this in fuzz tests. In the fuzz tests, we can perform operations on the type that uses the deterministic storage, wait until it fails, and then assert that the resulting state is recoverable.

### PR DESCRIPTION
**Pull request by danlaine**
Resolves #2911.

* Adds `commonware-runtime::faulty::Storage` which implements `commonware-runtime::Storage`. This implementation wraps an underlying storage implementation and, based on its config and an RNG, deterministically injects failures.
* Adds `commonware-runtime::faulty::Blob`, the associated `Blob` type for `commonware-runtime::faulty::Storage`.
* Adds fuzz tests `storage/fuzz/fuzz_targets/journal_crash_recovery.rs` and `storage/fuzz/fuzz_targets/mmr_journaled_crash_recovery.rs` to fuzz crash (i.e. stop after failed/partial write) contiguous journals and journaled MMRs respectively.

### CODE REVIEW

File: runtime/src/deterministic.rs [hunk 1]
```diff
@@ -844,10 +860,21 @@ impl Context {
             .timeout
             .map(|timeout| start_time.checked_add(timeout).expect("timeout overflowed"));
         let auditor = Arc::new(Auditor::default());
+
+        // Create shared RNG (used by both executor and storage)
+        let rng = Arc::new(Mutex::new(cfg.rng));
+
+        // Create storage fault config (default to disabled if None)
+        let storage_fault_config = Arc::new(RwLock::new(cfg.storage_faults.unwrap_or_default()));
```
Comment (patrick-ogrady) [inline runtime/src/deterministic.rs]: If there is a default, should we just set that in the config?

File: runtime/src/storage/faulty.rs [hunk 2]
```diff
@@ -0,0 +1,698 @@
...
+use std::{
+    io::Error as IoError,
+    sync::{
+        atomic::{AtomicU64, Ordering},
+        Arc, Mutex, RwLock,
+    },
+};
+
+/// Type alias for a boxed dynamic RNG.
+pub type BoxDynRng = Box<dyn CryptoRngCore + Send + 'static>;
```
Comment (patrick-ogrady) [inline runtime/src/storage/faulty.rs]: Is this already defined somewhere?

File: runtime/src/deterministic.rs (hunk 1 above)
Comment (danlaine) [reply runtime/src/deterministic.rs]: Removed `Option`

File: runtime/src/storage/faulty.rs (hunk 2 above)
Comment (danlaine) [reply runtime/src/storage/faulty.rs]: Right you are, removed

File: storage/fuzz/fuzz_targets/journal_crash_recovery.rs [hunk 3]
```diff
@@ -0,0 +1,594 @@
...
+}
+
+fn bounded_write_buffer(u: &mut Unstructured<'_>) -> Result<usize> {
+    u.int_in_range(1..=MAX_WRITE_BUF)
+}
+
+fn bounded_nonzero_rate(u: &mut Unstructured<'_>) -> Result<f64> {
+    let percent: u8 = u.int_in_range(1..=100)?;
+    Ok(f64::from(percent) / 100.0)
+}
```
[the remark this answers is not in the document]
Comment (danlaine) [reply storage/fuzz/fuzz_targets/journal_crash_recovery.rs:50]: Eh, I think that might be overkill. We've tolerated a fair bit of repetition in fuzz tests to this point. I think keeping these (trivial) helpers in the files where they're used makes the test files somewhat more readable/self-documenting.

File: runtime/src/deterministic.rs [hunk 4]
```diff
@@ -42,14 +42,15 @@
 //! });
 //! ```
 
+pub use crate::storage::faulty::FaultConfig;
```
Comment (patrick-ogrady) [inline runtime/src/deterministic.rs]: nit: `::Config as FaultConfig`?

File: runtime/src/storage/faulty.rs [hunk 5]
```diff
@@ -0,0 +1,694 @@
...
+    io::Error as IoError,
+    sync::{
+        atomic::{AtomicU64, Ordering},
+        Arc, Mutex, RwLock,
+    },
+};
+
+/// Operation types for fault injection.
+#[derive(Debug, Clone, Copy, PartialEq, Eq)]
+enum FaultOp {
```
Comment (patrick-ogrady) [inline runtime/src/storage/faulty.rs]: nit: `Op`

File: runtime/src/storage/faulty.rs [hunk 6]
```diff
@@ -0,0 +1,694 @@
...
+    Resize,
+    Remove,
+    Scan,
+}
+
+/// Configuration for deterministic storage fault injection.
+///
+/// Each rate is a probability from 0.0 (never fail) to 1.0 (always fail).
+#[derive(Clone, Debug, Default)]
+pub struct FaultConfig {
```
Comment (patrick-ogrady) [inline runtime/src/storage/faulty.rs]: nit: `Config`

File: runtime/src/storage/faulty.rs [hunk 7]
```diff
@@ -0,0 +1,694 @@
...
+    /// Set the scan failure rate.
+    pub const fn scan(mut self, rate: f64) -> Self {
+        self.scan_rate = Some(rate);
+        self
+    }
+}
+
+/// Shared fault injection context.
+#[derive(Clone)]
+struct FaultCtx {
```
Comment (patrick-ogrady) [inline runtime/src/storage/faulty.rs]: nit: `Oracle`

File: runtime/src/storage/faulty.rs (hunk 5 above)
Comment (danlaine) [reply runtime/src/storage/faulty.rs]: Done

File: runtime/src/storage/faulty.rs (hunk 6 above)
Comment (danlaine) [reply runtime/src/storage/faulty.rs]: Done

File: runtime/src/storage/faulty.rs (hunk 7 above)
Comment (danlaine) [reply runtime/src/storage/faulty.rs]: Done
